### ISSUE TITLE
Templates in the wrong folder ? (EE 1.13.1)

### ISSUE THREAD

**Issue by leiluspocus** [AOEpeople/Aoe_Scheduler#103]
Hi,
 
I have just updated the module to its last version (I'm still using Magento EE 1.13.1). The page "Instructions" wasn't displayed (a blank page was displayed instead). 

I found out that Magento was looking for template in the adminhtml/base/default folder (and not in default/default). When I copied/pasted the templates in the 'base/default' folder, the page "Instructions" appeared correctly. 

I guess it's specific to EE ? 

Thanks !

**Comment by fbrnc** [comment]
Hi,

that's strange. While for the **frontend** area third-party modules should store their layout and template files in `base/default` for **adminhtml** everything (including Magento's core layout files and templates" live in `default/default`. I've tested it with a Magento EE 1.13 instance and the instructions page looks fine.

I assume in your Magento instance the admin package/theme might be overwritten to enable any customizations. This will bypass the `default/default` theme. So now the question is if it is a general good practice to also store admin templates and themes in `base/default` instead to account for the (a lot less common) siturations where people have custom backend themes. 
Would this have any side effects? If not why isn't Magento and any other module provide putting it's templates there?).

Does anybody have an idea/optionon/suggestion about this?

**Comment by mzeis** [comment]
We also put templates files for **adminhtml** in `default/default`. It works for us and the "Instructions" page is working for me in the latest version.
