### ISSUE TITLE
Watchdog cronjob instruction: suggest cd to shell/ directory

### ISSUE THREAD

**Issue by mzeis** [AOEpeople/Aoe_Scheduler#104]
The "Instructions" page suggests this crontab definition:

    */10 * * * * /usr/bin/php /path/to/magento/shell/scheduler.php --action watchdog

When the extension is installed via modman/Composer and symlinked into the Magento core this call will fail with the message

    PHP Fatal error:  require_once(): Failed opening required 'abstract.php' (include_path='.:/usr/share/pear:/usr/share/php') in /path/to/.modman/Aoe_Scheduler/shell/scheduler.php on line 3

We defined the crontab like this:

    */10 * * * * cd /path/to/magento/shell/ && /usr/bin/php /path/to/magento/shell/scheduler.php --action watchdog

**Comment by fbrnc** [comment]
Good point! I missed that one. Also I've added the maintenance flag check (if selected)

**Comment by lfolco** [comment]
I'm still seeing the watchdog error from some reason:

PHP Warning:  require_once(abstract.php): failed to open stream: No such file or directory in /data/websites/example.com/vendor/aoepeople/aoe_scheduler/shell/scheduler.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'abstract.php' (include_path='.:/usr/share/php:/usr/share/pear') in /data/websites/example.com/vendor/aoepeople/aoe_scheduler/shell/scheduler.php on line 3

my folder structure has composer packages in vendor and the site in a sibling folder, 'public'.

**Comment by fbrnc** [comment]
Hi @lfolco ,

if you update Aoe_Scheduler you should now see the fixed instructions. The issue is that you have to `cd` into the `shell` directory first.

So something like this should work for you:

```
10 * * * * cd /data/websites/example.com/public/shell/ && /usr/bin/php scheduler.php --action watchdog
```

**Comment by brandontamm** [comment]
@fbrnc - I am using Docker to separate my services (nginx, magento/php, mysql) and composer to install your module. I cannot get crontab to run scheduler. My assumption is that the file path is goofy due to docker and composer symlink. Here is what I am seeing from the instructions:
* * * * * ! test -e /var/www/html/web/maintenance.flag && /bin/bash /var/www/html/web/scheduler_cron.sh --mode always
* * * * * ! test -e /var/www/html/web/maintenance.flag && /bin/bash /var/www/html/web/scheduler_cron.sh --mode default

However, when I check the absolute path of that file, it is:
/root/quickattach/vendor/aoepeople/aoe_scheduler/scheduler_cron.sh

Can you help me figure out what command I should be using? Do I have to cd into directory first?

**Comment by brandontamm** [comment]
also, my file path to the symlink is:
/root/quickattach/web/scheduler_cron.sh

**Comment by LeeSaferite** [comment]
@brandontamm What is the error you are getting exactly?

**Comment by brandontamm** [comment]
@LeeSaferite - Heartbeat is not running. Even when I manually start the heartbeat, it never stays running so I know the crontab instructions are not working. I swear it's just a file path issue that I haven't been able to figure out. I'm ready to tear my hair out  :(

**Comment by LeeSaferite** [comment]
What happens when you run it manually?

    sudo -u {web server user} bash /var/www/html/web/scheduler_cron.sh --mode default

Is that producing any errors?
Is the aoeschedule_heartbeat job being scheduled to run?

**Comment by brandontamm** [comment]
@LeeSaferite - Any ideas which container I should run that command in? Also, my nginx is running as user: nginx, should I use that or www-data?

I am using Andreas' Koch's Dockerized-Magento project, which pulls aoescheduler in via composer...The nginx, php and mysql services are separated into containers, although the Magento app 'volume' is present on all containers. I think that is my issue, so I have been trying now to run the command manually in each container and using different file paths until I get something to work so I can figure out how to get crontab running in the appropriate container and with the appropriate file path - it's been a nightmare...

**Comment by brandontamm** [comment]
@LeeSaferite - These are my attempts at running your command

root@QAStaging:~/quickattach# sudo -u nginx bash /var/www/html/web/scheduler_cron.sh --mode default
sudo: unknown user: nginx
sudo: unable to initialize policy plugin
root@QAStaging:~/quickattach# sudo -u www-data bash /var/www/html/web/scheduler_cron.sh --mode default
bash: /var/www/html/web/scheduler_cron.sh: No such file or directory
root@QAStaging:~/quickattach# sudo -u www-data bash /root/quickattach/web/var/www/html/web/scheduler_cron.sh --mode default
bash: /root/quickattach/web/var/www/html/web/scheduler_cron.sh: Permission denied
root@QAStaging:~/quickattach# sudo -u nginx bash /root/quickattach/web/var/www/html/web/scheduler_cron.sh --mode default
sudo: unknown user: nginx
sudo: unable to initialize policy plugin
root@QAStaging:~/quickattach# sudo -u root bash /root/quickattach/web/var/www/html/web/scheduler_cron.sh --mode default
bash: /root/quickattach/web/var/www/html/web/scheduler_cron.sh: No such file or directory
root@QAStaging:~/quickattach# ls
composer.json  composer.lock  config  data  docker-compose.yml  docker-images  documentation  LICENSE  logs  magento  README.md  vendor  web
root@QAStaging:~/quickattach# cd web
root@QAStaging:~/quickattach/web# ls
api.php        cron.php  downloader   get.php            index.php         js               LICENSE_EE.html  LICENSE.txt  php.ini.sample  RELEASE_NOTES.txt  sitemap.xml
app            cron.sh   errors       GSF_UserGuide.pdf  index.php.sample  lib              LICENSE_EE.txt   mage         privatesales    scheduler_cron.sh  skin
composer.json  dev       favicon.ico  includes           install.php       LICENSE_AFL.txt  LICENSE.html     media        README.md       shell              var
root@QAStaging:~/quickattach/web#

**Comment by LeeSaferite** [comment]
You could try

   docker exec -it php sudo -u www-data bash /var/www/html/web/scheduler.sh --mode default

**Comment by brandontamm** [comment]
@LeeSaferite - A Docker fan :) No luck though!


root@QAStaging:~/quickattach/web# docker exec -it php sudo -u www-data bash /var/www/html/web/scheduler.sh --mode default
Error response from daemon: No such container: php
root@QAStaging:~/quickattach/web# docker exec -it quickattach_php_1 sudo -u www-data bash /var/www/html/web/scheduler.sh --mode default
exec: "sudo": executable file not found in $PATH
root@QAStaging:~/quickattach/web# docker exec -it quickattach_installer_1 sudo -u www-data bash /var/www/html/web/scheduler.sh --mode default
exec: "sudo": executable file not found in $PATH

**Comment by brandontamm** [comment]
@LeeSaferite - Any other ideas? I noticed we were trying with scheduler.sh but the file is called scheduler_cron.sh

I'm trying random attempts at anything lol

**Comment by LeeSaferite** [comment]
Try this one

   docker exec -it quickattach_php_1 su -s /bin/bash -c "bash /var/www/html/web/scheduler_cron.sh --mode default" www-data

**Comment by brandontamm** [comment]
@LeeSaferite - I think we are getting closer. I ran that command and got this error:
root@QAStaging:~/quickattach# docker exec -it quickattach_php_1 su -s /bin/bash -c "bash /var/www/html/web/scheduler_cron.sh --mode default" www-data
sh: 1: -t: not found

I got that same error when running this command:
root@QAStaging: docker exec -it quickattach_php_1 bash /var/www/html/web/scheduler_cron.sh --mode default
sh: 1: -t: not found

Also - I got no error when running this command inside the actual PHP container:
root@0bb0c837c42d:/var/www/html# bash /var/www/html/web/scheduler_cron.sh

**Comment by LeeSaferite** [comment]
Well, if you can run it which inside the exec attached to the container then I wouldn't worry.

So, back to my original question, after running that do you see the heartbeat task scheduled to run?

**Comment by brandontamm** [comment]
although i ran the command inside the php container without an error the first time, i have not seen the heartbeat show as working in the last 20 minutes.

So i tried again and got an error in the container that I didn't get before - it's the same errors we are getting with the 'docker exec' commands:
root@0bb0c837c42d:/var/www/html# bash /var/www/html/web/scheduler_cron.sh
sh: 1: -t: not found

**Comment by brandontamm** [comment]
Checked /var/log/syslog on the host:
Feb 11 16:26:01 QAStaging CRON[15517]: (www-data) CMD (! test -e /var/www/html/web/maintenance.flag && /bin/bash /var/www/html/web/scheduler_cron.sh --mode always)
Feb 11 16:26:01 QAStaging CRON[15513]: (CRON) info (No MTA installed, discarding output)
Feb 11 16:26:01 QAStaging CRON[15514]: (CRON) info (No MTA installed, discarding output)

**Comment by LeeSaferite** [comment]
Try running the scheduler PHP directly then.

    cd -P /var/www/html/web/shell
    php scheduler.php --action cron --mode default

**Comment by brandontamm** [comment]
Same error:

root@QAStaging:~/quickattach# ./magento enter php
root@0bb0c837c42d:/var/www/html# cd -P /var/www/html/web/shell
root@0bb0c837c42d:/var/www/html/web/shell# php scheduler.php --action cron --mode default
sh: 1: -t: not found

**Comment by LeeSaferite** [comment]
Ok. you have a problem somewhere else then. That shouldn't be something that scheduler is generating. 

What *exact* version are you running?

**Comment by brandontamm** [comment]
"aoepeople/aoe_scheduler": "v1.3.1",

**Comment by brandontamm** [comment]
@LeeSaferite ... Trying anything again :) The command you provided above worked once again, and then produced an error on the second attempt:
root@QAStaging:~# docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default
root@QAStaging:~# docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default
sh: 1: -t: not found

am I right in assuming that because there was no echo or output from the first command, that it worked?

**Comment by brandontamm** [comment]
@LeeSaferite - I'm in the docker chatroom too and someone mentioned that we're on the right track with those last codes...they said "somewhere there is a '-t' that it doesn't like"

**Comment by brandontamm** [comment]
@LeeSaferite - I found this and am working on editing the php.ini file because it looks like thats the root according to: http://axiac.ro/blog/2013/06/sh-1-t-not-found/

**Comment by brandontamm** [comment]
@LeeSaferite - I figured out what it was. The article above had me add the following line to php.ini:
sendmail_path=sendmail -t -i

I did that, rebuilt my containers last night, and then I was getting this error:
sh: 1: sendmail: not found

I fixed the error and got CRON running by adding the following to the CRONTAB:
MAILTO=""

I assume CRON wants to send mail when jobs run or fail, so I think the people that are having the "No Heartbeat" problem are new to CRON (like me) and didn't check the box to Receive Email notifications. 
If that's truly the case, I think MAILTO="" should be the default in your instructions for the extension, and if the Email Notification box is checked in the instruction admin screen, then the instructions should include the email address to that code.

Hopefully I help someone else with this - I lost three days and was ready to quit using Docker because I was so intent it was a Docker problem :)

**Comment by brandontamm** [comment]
@LeeSaferite - Nevermind, I jumped the gun. I can run this command without the errors mentioned above:
docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default

However, the heartbeat is still not working every 5 minutes :( Any ideas?

Here's what my CRONTAB looks like:
MAILTO=""
* * * * * ! test -e /var/www/html/web/maintenance.flag && /bin/bash /var/www/html/web/scheduler_cron.sh --mode always
* * * * * ! test -e /var/www/html/web/maintenance.flag && /bin/bash /var/www/html/web/scheduler_cron.sh --mode default

**Comment by LeeSaferite** [comment]
So, back to my original question then, after running it manually do you see the heartbeat job in the pending schedule?

**Comment by brandontamm** [comment]
Yes I can see the heartbeat cron in the timeline pending schedule. It is there, but it is missing it's scheduled times to run.

I also edited the crontab so it looks like this:
MAILTO=""
* * * * * ! test -e /root/quickattach/web/maintenance.flag && docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default
* * * * * ! test -e /root/quickattach/web/maintenance.flag && docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default

It is not working before edit and now again after this edit.

**Comment by LeeSaferite** [comment]
For non-production testing you can easily drop that maintenance.flag check.

This would be used inside the container

    * * * * * www-data /bin/bash /var/www/html/web/scheduler_cron.sh --mode always
    * * * * * www-data /bin/bash /var/www/html/web/scheduler_cron.sh --mode default

This would be used outside the container

    * * * * * docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode default    
    * * * * * docker exec -itu www-data quickattach_php_1 /bin/bash /var/www/html/web/scheduler_cron.sh --mode always

**Comment by brandontamm** [comment]
I put the "outside the container" version in the crontab, restarted cron, ran the command manually, and waited - still no heartbeat in 10 minutes. I tried to the following commands unsuccessfully to edit the crontab from inside the container:

root@074b23fb9694:/var/www/html# sudo crontab -u www-data -e
bash: sudo: command not found
root@074b23fb9694:/var/www/html# crontab
bash: crontab: command not found
root@074b23fb9694:/var/www/html# crontab -e
bash: crontab: command not found
root@074b23fb9694:/var/www/html# sudo crontab -u nginx -e
bash: sudo: command not found

**Comment by LeeSaferite** [comment]
The fact that you don't see any scheduled runs for the heartbeat task is an issue. Ever time the schedule run in 'default' mod it *should* be triggering the scheduling process and the heartbeat task should have scheduled job entries after this happens.

First, let's see if your heartbeat is even able to run. From the *Jobs Configuration* page, click the box by the *aoescheduler_heartbeat* task and then, using the top-right dropdown, select the *Schedule Now* action and click *Submit*. This will manually create a scheduled run of the heartbeat task. If this works you should be able to see the aoeschedule_heartbeat task with a scheduled run in either the timeline or list view. Wait for 1-2 minutes (with your cron process running) and the job should run and be marked as finished. If this works then it's just schedule generation problem.

If it's a schedule generation problem:
Ensure that the config value for 'system/cron/logFile' is set to a file name. This enables internal logging for scheduler. This should result in a log entry every time the scheduler generates new scheduled jobs. You'll find this output in the file specified by 'system/cron/logFile'. You should see an entry like "Generated schedule. Newest task is scheduled a" and some more text after. If you do not see this then the generateSchedules method didn't run. This method has a precondition it checks to prevent it from generating schedules on every call. It stores the last call time in Magento's cache and uses this to limit scheduling frequency. The default limit for this is 15 minutes.

If it is *not* a schedule generation problem then we'll need to do some more debugging.

**Comment by brandontamm** [comment]
I probably didn't explain that well enough - after manually running the 'docker exec' command, I can see the heartbeat cron with 4 pending runs in the timeline/schedule. They never change from pending status so they aren't running.

I tried the first method you listed above - the schedule is made and I can see the heartbeat tasks with schedule run in timeline and list, but the job doesn't run or get marked as finished.

Contents of cron.log after running manual 'docker exec' command:
2016-02-12T17:07:23+00:00 DEBUG (7): Start: enterprise_staging_automates
2016-02-12T17:07:23+00:00 DEBUG (7): Stop: enterprise_staging_automates
2016-02-12T17:07:23+00:00 DEBUG (7): Start: core_email_queue_send_all
2016-02-12T17:07:23+00:00 DEBUG (7): Stop: core_email_queue_send_all

Contents of cron.log after Generating Schedule from Magento Admin:
2016-02-12T17:08:37+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:08:00" already exists 1 times. Skipping.
2016-02-12T17:08:37+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:08:00" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "aoescheduler_heartbeat" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "aoescheduler_heartbeat" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "aoescheduler_heartbeat" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "captcha_delete_expired_images" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "captcha_delete_expired_images" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:11" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:12" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:13" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:14" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:16" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:17" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:18" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:19" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "core_email_queue_send_all" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "ebizmarts_abandoned_cart" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "ebizmarts_abandoned_cart" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "ebizmarts_abandoned_cart" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:11" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:12" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:13" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:14" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:16" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:17" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:18" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:19" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "enterprise_staging_automates" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "magemonkey_sendorders_asynch" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "magemonkey_sendsubscribers_asynch" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "newsletter_send_all" at "2016-02-12 17:10" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "newsletter_send_all" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "newsletter_send_all" at "2016-02-12 17:20" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Pending schedule for "send_notification" at "2016-02-12 17:15" already exists 1 times. Skipping.
2016-02-12T17:09:35+00:00 DEBUG (7): Generated schedule. Newest task is scheduled at "2016-02-12 17:28:00". (Duration: 0.62 sec)

What's next?

**Comment by brandontamm** [comment]
I think I figured out where we have to focus on again. I noticed a PHP stack trace error in exception.log relating to AOESCHEDULER and sendmail, but I didn't know from what attempt we've tried so many things, so I cleared out the file and tried using the generate and schedule now functions again. No errors, so I went back into config and added my email address into config and now when I try to run the 'docker exec' commands manually i am getting the sh: 1: sendmail: not found error again. 

This was the error I fix by adding MAILTO="" in the crontab, so now the extension must be trying to send from Magento sendmail.

I planned on using Mandrill for all email related items, so I added my API key and set that up and I don't see it coming through on Mandrill.....

Soo, I think the code in the extension is somehow still trying to use sendmail and that's why we the manual 'docker exec' code works (without the email address added in config) and why the admin never works to run cron on the scheduled timeline.

**Comment by brandontamm** [comment]
@LeeSaferite - I searched through the code in the extension and can't find anything that would be causing the sendmail - any ideas?

**Comment by brandontamm** [comment]
@LeeSaferite - Hope you had a good weekend - any ideas where to go from here?

**Comment by brandontamm** [comment]
@LeeSaferite - FYI it was a super simple fix. Needed to run ./magento magerun sys:setup:run and then manually run the scheduler. It is now scripted into the docker project build so let me know if you run into this again and want me to share some of that code (private repo.)
