### ISSUE TITLE
Duplicate column name 'scheduled_by' and 'scheduled_reason'

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#109]
### Error in file: "/var/www/example/production/releases/build_299/htdocs/app/code/community/Aoe/Scheduler/sql/aoescheduler_setup/mysql4-upgrade-0.5.0-0.5.1.php" - SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'scheduled_by'

```
Trace:
#0 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '0.4.3', '1.0.1')
#2 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('0.4.3', '1.0.1')
#3 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /var/www/example/production/releases/build_299/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /var/www/example/production/releases/build_299/htdocs/index.php(87): Mage::run('', 'store')
#8 {main}
```

### Error in file: "/var/www/example/production/releases/build_299/htdocs/app/code/community/Aoe/Scheduler/sql/aoescheduler_setup/mysql4-upgrade-0.5.0-0.5.1.php" - SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'scheduled_reason'

```
Trace:
#0 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '0.4.3', '1.0.1')
#2 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('0.4.3', '1.0.1')
#3 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/example/production/releases/build_299/htdocs/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /var/www/example/production/releases/build_299/htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /var/www/example/production/releases/build_299/htdocs/index.php(87): Mage::run('', 'store')
#8 {main}
```

**Comment by fbrnc** [comment]
@LeeSaferite Could this be cause by the rolled up `install-1.0.0` that you introduced? 
Is there a chance that that script is actually called first AND afterwards the individual version upgrade script are run?
Just guessing, but I don't know how these two columns could possible already have been there since a very we updated a very old version of Aoe_Scheduler in the project I'm seeing this (and that version wasn't even the previous task_records branch)

**Comment by LeeSaferite** [comment]
First, the rollup script is not the problem here. It only gets run if the module has never been installed. The only scripts after the rollup install script would be ones that upgrade sequentially after.

Second, you shouldn't even GET this error. Something is very wrong on that server perhaps. I say this becasue the script calls `$installer->getConnection()->addColumn()` which internally calls `tableColumnExists()` to see if the column is there and exit fast with a `true` if it did exists. That means that it should never get that SQL error.

So, even if the columns DO exist already, you should never see that error message.

**Comment by LeeSaferite** [comment]
Closing as this is not reproducible
