### ISSUE TITLE
"crontab/..." entries in core_config_data gets wiped out

### ISSUE THREAD

**Issue by SchumacherFM** [AOEpeople/Aoe_Scheduler#112]
https://twitter.com/schumacherfm/status/583080191683010560

This issue is in relation to #106 and #89 

Using Magento 1.8.1 with Scheduler from `master` branch with this version https://github.com/AOEpeople/Aoe_Scheduler/commit/6c06a4fd89c702c36205a5c0d359cc3d1ba69ed9

I've finally found out that the entries with path 'crontab/...' in table `core_config_data` will get removed when I disable a random job in `admin/job/index`. There is no error, nothing. It also only occurs after a specific time. I guess something related to cache (Using Redis). Right after cleared caches all works fine.

In addition the missing entries in `core_config_data` will sometimes occur automatically. Very strange.

I cannot reproduce this error in my dev and staging region with Mage 1.9.1 and the latest commit from `master` branch.

I'll do an overwrite tomorrow on production with the latest commit of *Aoe_Scheduler*. I have no other idea to track that race? condition. I'll report back.

**Comment by fbrnc** [comment]
A desperate (and ugly) way to shed some light into this could be to log all MySQL queries that contain `core_config_data` in `lib/Varien/Db/Adapter/Pdo/Mysql.php` and see what exact query might be erasing those records.

**Comment by SchumacherFM** [comment]
55MB log file with back traces.

Added logging at 2015-04-01 21:35:02 UTC.

```
2015-04-01 22:00:04 UTC: DELETE FROM `core_config_data` WHERE (path LIKE 'crontab/jobs/catalog_product_alert%')


#0 /usr/share/nginx/html/semver/htdocs/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/nginx/html/semver/htdocs/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /usr/share/nginx/html/semver/htdocs/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /usr/share/nginx/html/semver/htdocs/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `co...', Array)
#4 /usr/share/nginx/html/semver/htdocs/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `co...', Array)
#5 /usr/share/nginx/html/semver/htdocs/lib/Zend/Db/Adapter/Abstract.php(661): Varien_Db_Adapter_Pdo_Mysql->query('DELETE FROM `co...')
#6 /usr/share/nginx/html/semver/htdocs/app/code/community/Ho/Import/Model/Resource/System/Import/Collection.php(114): Zend_Db_Adapter_Abstract->delete('core_config_dat...', 'path LIKE 'cron...')
#7 /usr/share/nginx/html/semver/htdocs/app/code/community/Ho/Import/Model/Observer.php(33): Ho_Import_Model_Resource_System_Import_Collection->cleanupCron()
#8 [internal function]: Ho_Import_Model_Observer->schedule(Object(Aoe_Scheduler_Model_Schedule))
#9 /usr/share/nginx/html/semver/htdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(163): call_user_func_array(Array, Array)
#10 /usr/share/nginx/html/semver/htdocs/app/code/community/Aoe/Scheduler/Model/Schedule.php(541): Aoe_Scheduler_Model_Schedule->runNow(true)
#11 /usr/share/nginx/html/semver/htdocs/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#12 /usr/share/nginx/html/semver/htdocs/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#13 /usr/share/nginx/html/semver/htdocs/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#14 /usr/share/nginx/html/semver/htdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#15 /usr/share/nginx/html/semver/htdocs/cron.php(76): Mage::dispatchEvent('default')
#16 {main}
```

This happens 12 times.

Holy $@*&^$# 💩 ... Did you see it !? Here is the [conflicting name space](https://github.com/ho-nl/Ho_Import/blob/master/app%2Fcode%2Fcommunity%2FHo%2FImport%2FModel%2FResource%2FSystem%2FImport%2FCollection.php#L92).

Guys @mzeis, @dbashyal, @tegansnyder and @LeeSaferite do you also have Ho_Import running?

I suggest that @paales must be involved into finding a solution :laughing:

**Comment by fbrnc** [comment]
Good job finding this @SchumacherFM!

In version 0.1.0 of Aoe_Scheduler we added the ability to create new job configuration that live in the database or override existing ones defined in XML. We also migrated the "disabled jobs" feature to now be handled this way. Of course deleting all those records will make Aoe_Scheduler forget about the jobs that have been deleted and also forget about any other configuration you might have edited or added in the backend.

The  thing is that we didn't introduce the concept of storing things in crontab/jobs/ in core_config_data. Magento was already doing this and actually other modules were also using this mechanism. The new version of Aoe_Scheduler basically only introduces the missing UI to edit those records.

So even without using Aoe_Scheduler it's not safe to just delete all those records. Ho_Import was most likely messing with all the other modules that have been relying on this before. I assume simply nobody ever noticed. 

I'm not sure why https://github.com/ho-nl/Ho_Import/blob/master/app%2Fcode%2Fcommunity%2FHo%2FImport%2FModel%2FResource%2FSystem%2FImport%2FCollection.php#L92-118 is there in the first place, but I'm sure there must be a better way to solve whatever problem this is trying to solve without deleting all cron configurations.

Is this module creating new cron configuration dynamically? Maybe to accomodate different parameters? If so this actually now can be done with Aoe_Scheduler in probably a much cleaner way. But I also understand if you don't want Ho_Import to depend on Aoe_Scheduler being there. In any case then the dynamically created configurations should probably be prefixed and the cleanup task should only touch those.

**Comment by mzeis** [comment]
@SchumacherFM Good catch! No, we don't use Ho_Import yet. I started experimenting with it but funnily enough we didn't have to create a new importer since then.

**Comment by paales** [comment]
> Is this module creating new cron configuration dynamically? Maybe to accomodate different parameters? If so this actually now can be done with Aoe_Scheduler in probably a much cleaner way. But I also understand if you don't want Ho_Import to depend on Aoe_Scheduler being there. In any case then the dynamically created configurations should probably be prefixed and the cleanup task should only touch those.

We are indeed creating cron's dynamically. We allow you to set the cron schedule in the import profile and we move the import profile to the cron schedule. Apparently I clean up very thoroughly ;)

**Comment by paales** [comment]
The issue is resolved in Ho_Import.

**Comment by SchumacherFM** [comment]
:+1:  :clap:
