### ISSUE TITLE
1.4.2

### ISSUE THREAD

**Issue by aydus** [AOEpeople/Aoe_Scheduler#114]
Encountered these issues during install to 1.4.2:

In mysql4-upgrade-0.5.0-0.5.1, the params for Varien_Db_Adapter_Pdo_Mysql addColumn are all strings 

<pre>
<code>
    /**
     * Add new column to table
     *
     * @param   string $tableName
     * @param   string $columnName
     * @param   string $definition
     * @return  bool
     */
    public function addColumn($tableName, $columnName, $definition)
</code>
</pre>

In mysql4-upgrade-0.5.3-0.5.4.php, dropTable is not a method:

<pre>
<code>
$this->getConnection()->dropTable($this->getTable('cron_job'));
</code>
</pre>

**Comment by fbrnc** [comment]
Hi @aydus,
looks like Aoe_Scheduler 1.x isn't compatible with Magento 1.4 anymore. We're only testing starting from Magento CE 1.4 and EE 1.11.

Even if you'd get past this issue during the installer you might run into other issues. 
If you really need to continue to use  Magento 1.4 you can install an older version of Aoe_Scheduler.
Version 0.4.4 should still be compatible with Magento 1.4. You can download it from here: https://github.com/AOEpeople/Aoe_Scheduler/releases

**Comment by aydus** [comment]
Thanks
