### ISSUE TITLE
Magento Compilation Mode breaks AOE_scheduler

### ISSUE THREAD

**Issue by pddc** [AOEpeople/Aoe_Scheduler#116]
as soon as I enable compilation mode, I get the following error

Fatal error: Class 'Aoe_Scheduler_Controller_AbstractController' not found in /var/www/fanvision/app/code/community/Aoe/Scheduler/controllers/Adminhtml/SchedulerController.php on line 8

installed by untar, not by composer, not sure it makes a difference

thanks

**Comment by fbrnc** [comment]
Hi @pddc,
it's not recommended to use the Magento Compiler in the first place (I think it actually has been kind-of "officially" discontinued). 
However, there's nothing I can do on the Aoe_Scheduler side even if I wanted to support the Compiler.
But it's exactly problems like this (Magento Compiler is copying files around and modifying the source code) that makes the Magento Compiler a really bad idea.
If you're looking for a solution to the code pool lookup (that's what the Magento Compiler is trying to optimize in the first place) check Aoe_ClassPathCache.
Cheers,
Fabrizio
