### ISSUE TITLE
Random duplicate schedules at the time of schedule generation

### ISSUE THREAD

**Issue by nemphys** [AOEpeople/Aoe_Scheduler#117]
Having set the schedule generation interval to 30 minutes and the schedule-ahead interval to 60 minutes, something weird happens:

As seen on the attached grid images, the schedule generator creates a new schedule instance for all jobs at the time of its execution (actually, if it executed eg. at 15:30:01, it creates a new schedule for all jobs for 15:30:00 although there is already an existing one that gets executed at the right time), which is executed 1 minute later (on the next pass, since I run the cron every minute, as proposed).
The weird thing is that this does not seem to happen on *every* schedule generation, it happens sometimes.

I am thinking it must have something to do with the fact the schedules are generated *after* the jobs are executed and the generateSchedulesForJob() method of ScheduleManager is checking for *pending* jobs with $ts = strftime('%Y-%m-%d %H:%M:00', $time); (zeroing out the seconds). That means that if the schedule is run at 12:00:02, it will look for pending jobs scheduled for 12:00:00 and since the will not been found (remember, they are not pending anymore, so they are not included in the query results), it will generate them again (and they will be executed again on the next execution pass).
The easy solution might be to generate the schedules *before* running the jobs (in Observer's dispatch() method), but I didn't look deep for any negative consequences of a change like that. Otherwise, the query logic in generateSchedulesForJob must be adjusted to skip the executed jobs mentioned above.

I hope I at least pointed at the right direction...

![aoe_schedule1](https://cloud.githubusercontent.com/assets/739270/7141991/c93a5b40-e2dd-11e4-81b8-8e0276b4b53f.jpg)
![aoe_schedule2](https://cloud.githubusercontent.com/assets/739270/7141990/c90cb2c6-e2dd-11e4-87f7-3ecc2f7fd5eb.jpg)

**Comment by nemphys** [comment]
FYI, I just added a +60 to the initial $time value in generateSchedulesForJob's for loop and the problem went away (-> "for ($time = $now + 60; $time < $timeAhead; $time += 60) {").
It makes sense to start checking from the next minute and not the current, since the scheduling takes place after all jobs have been executed, so there should never be a pending job for the current minute.

**Comment by leiluspocus** [comment]
Had the same problem, applied your patch, worked like a charm ! Thank you @nemphys :)

**Comment by dorrogeray** [comment]
Hi, thanks for the patch, it works! We faced the same issue. Duplicate schedules would be generated at the time of schedule generation..

**Comment by fbrnc** [comment]
Thank you @dorrogeray / @nemphys. Just merged the pull request.

**Comment by kweij** [comment]
Hi @fbrnc, I (and at least @dorrogeray) are still running into the same issue. The fix of +30 seconds is not adequate, pull-request (https://github.com/AOEpeople/Aoe_Scheduler/pull/215) needs to be merged in order to fully resolve this bug.

And while you're at it, please release a version with the mentioned fix in it.
