### ISSUE TITLE
AOE Schedule pages empty - working in DEV, but not PRODUCTION

### ISSUE THREAD

**Issue by runehorneland** [AOEpeople/Aoe_Scheduler#120]
Hi,
We have an issue with the Schedule pages being empty in our production-site.
It works in the DEV-site, which is a subfolder in the same physical website.

Have you come across this before? Will attach screenshot of working and non-working.
![2015-04-29 15_09_01-magento administrasjon](https://cloud.githubusercontent.com/assets/10116624/7391523/247c1c96-ee82-11e4-9582-dc1a252113fd.png)
![2015-04-29 15_09_38-magento administrasjon](https://cloud.githubusercontent.com/assets/10116624/7391524/247eb988-ee82-11e4-813e-634b626015ab.png)
![2015-04-29 15_12_41-behandle produkter _ katalog _ magento administrasjon](https://cloud.githubusercontent.com/assets/10116624/7391542/3e274620-ee82-11e4-8513-72a6ef8b45ef.png)

**Comment by leiluspocus** [comment]
Not sure it helps you but last time I had a similar error, it was because I moved the template files to the wrong place. 
But I guess you are using a versionned project? (I mean projects file are identical in dev and prod?)

**Comment by runehorneland** [comment]
Hi! Thanks, you're right. Just forgot files in the template & layout part.
