### ISSUE TITLE
Capture error_log

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#126]
When jobs die it's hard to find out why.
Here's an idea:
Before executing the job set php configuration (for this process only) to log everything to a process specific file (e.g. in var/log/scheduler/<jobid>.log)

Then - even if the job died because of a PHP fatal error - we can go back and see what has happened without digging into the log files (that might not exist in the first place) and find entries in the timespan in the past when this process might have died.

This information could also be displayed in the backend.

When cleaning up records the corresponding files should also be deleted.

**Comment by drobinson** [comment]
⇧ You might want to be able to configure this on a per-job basis.  Some jobs probably don't need this overhead.

**Comment by fbrnc** [comment]
Implemented (in version 1.1)
