### ISSUE TITLE
Fix grid filtering 

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#138]
See: https://github.com/AOEpeople/Aoe_Scheduler/commit/b7aabf9c1a24470c2b1455b2d14ac553e49a9ae4 

And: https://twitter.com/MaximeHuran/status/621339052311228416

**Comment by fbrnc** [comment]
@steverobbins Would you mind checking this?

**Comment by steverobbins** [comment]
@fbrnc On it

**Comment by fbrnc** [comment]
Wow, that was fast! Thank you very much!
