### ISSUE TITLE
No configuration found for code “..."

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#14]
When users install an extension that comes with a scheduler task and uninstall it the xml configuration might still be there (or in the cache) resulting Aoe_Scheduler to throw an exception.

This exception should be catched and displayed as a meaningful warning instead.

**Comment by fbrnc** [comment]
Hi @rzrz,
what exact query did you run? And what configuration code is Aoe_Scheduler complaining about? 
Did you uninstall the module that was providing this cron job? Are you sure every file from that module is gone? Did you clear all caches?

Cheers,
Fabrizio

**Comment by rzrz** [comment]
I received the email from AOE whenever cron is not working. I did uninstall the module and emailed the developer to help with this but I am still getting the email daily. Details as such:



Cron error while executing ordermanager_archive:

exception 'Mage_Core_Exception' with message 'No valid configuration found.' in /var/www/app/Mage.php:594
Stack trace:
#0 /var/www/app/code/community/Aoe/Scheduler/Model/Observer.php(36): Mage::throwException('No valid config...')
#1 /var/www/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#2 /var/www/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#3 /var/www/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('default', Array)
#4 /var/www/cron.php(71): Mage::dispatchEvent('default')
#5 {main}

**Comment by fbrnc** [comment]
This problem is solved now in version 1. You can see all the "leftovers" from previous modules in the Job configuration view and delete them there without accessing the database directly.
