### ISSUE TITLE
No configuration found for code "ordermanager_archive"

### ISSUE THREAD

**Issue by rzrz** [AOEpeople/Aoe_Scheduler#141]
After installing AOE on Magento 1.8, accessing the menu of AOE gave these messages:

How can I fix this? 

#0 /home/mywebsite/public_html/mywebsite_live/app/code/community/Aoe/Scheduler/Model/Configuration.php(81): Mage::throwException('No configuratio...')
#1 /home/mywebsite/public_html/mywebsite_live/app/code/community/Aoe/Scheduler/Model/Collection/Crons.php(25): Aoe_Scheduler_Model_Configuration-&gt;loadByCode('ordermanager_ar...')
#2 /home/mywebsite/public_html/mywebsite_live/lib/Varien/Data/Collection.php(622): Aoe_Scheduler_Model_Collection_Crons-&gt;loadData(false, false)
#3 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection-&gt;load()
#4 /home/mywebsite/public_html/mywebsite_live/app/code/community/Aoe/Scheduler/Block/Adminhtml/Cron/Grid.php(32): Mage_Adminhtml_Block_Widget_Grid-&gt;_prepareCollection()
#5 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): Aoe_Scheduler_Block_Adminhtml_Cron_Grid-&gt;_prepareCollection()
#6 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid-&gt;_prepareGrid()
#7 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(885): Mage_Adminhtml_Block_Widget_Grid-&gt;_beforeToHtml()
#8 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(605): Mage_Core_Block_Abstract-&gt;toHtml()
#9 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(549): Mage_Core_Block_Abstract-&gt;_getChildHtml('grid', true)
#10 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract-&gt;getChildHtml('grid')
#11 /home/mywebsite/public_html/mywebsite_live/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container-&gt;getGridHtml()
#12 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(241): include('/home/mywebsite/...')
#13 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template-&gt;fetchView('adminhtml/defau...')
#14 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template-&gt;renderView()
#15 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template-&gt;_toHtml()
#16 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template-&gt;_toHtml()
#17 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Adminhtml_Block_Widget_Container-&gt;_toHtml()
#18 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract-&gt;toHtml()
#19 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Core_Block_Text_List-&gt;_toHtml()
#20 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(605): Mage_Core_Block_Abstract-&gt;toHtml()
#21 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(549): Mage_Core_Block_Abstract-&gt;_getChildHtml('content', true)
#22 /home/mywebsite/public_html/mywebsite_live/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract-&gt;getChildHtml('content')
#23 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(241): include('/home/mywebsite/...')
#24 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template-&gt;fetchView('adminhtml/defau...')
#25 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template-&gt;renderView()
#26 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template-&gt;_toHtml()
#27 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Adminhtml_Block_Template-&gt;_toHtml()
#28 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract-&gt;toHtml()
#29 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout-&gt;getOutput()
#30 /home/mywebsite/public_html/mywebsite_live/app/code/community/Aoe/Scheduler/controllers/Adminhtml/AbstractController.php(21): Mage_Core_Controller_Varien_Action-&gt;renderLayout()
#31 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_AbstractController-&gt;indexAction()
#32 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action-&gt;dispatch('index')
#33 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard-&gt;match(Object(Mage_Core_Controller_Request_Http))
#34 /home/mywebsite/public_html/mywebsite_live/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front-&gt;dispatch()
#35 /home/mywebsite/public_html/mywebsite_live/app/Mage.php(683): Mage_Core_Model_App-&gt;run(Array)
#36 /home/mywebsite/public_html/mywebsite_live/index.php(96): Mage::run('', 'store')
#37 {main}<br />

**Comment by steverobbins** [comment]
I think this is exposing an issue with a module's cron setup.  It seems `ordermanager_archive` hasn't been properly configured.

Perhaps this error should be shown as a session error instead of throwing an exception.

**Comment by rzrz** [comment]
If that is the case would you advise what should I do in order to be able to use this extension?

**Comment by steverobbins** [comment]
That would best be asked on [http://magento.stackexchange.com/](http://magento.stackexchange.com/) since it's not an Aoe_Scheduler specific issue.

**Comment by fbrnc** [comment]
However is you know the correct callback this module intended to use you can edit the configured cron and insert it there. Or you just disable that job, since it's currently obviously not doing anything but producing errors...
In any case you might get an answer from the module author.
Feel free to reopen this issue if you think this is an issue with Aoe_Scheduler.
