### ISSUE TITLE
Change Tag "Latest release"

### ISSUE THREAD

**Issue by jhoelzl** [AOEpeople/Aoe_Scheduler#142]
Tag "Latest release" should go to version 1.2.0 instead of 1.0.1

**Comment by fbrnc** [comment]
Hi @jhoelzl,

first I thought about moving the "latest" tag (like I used to do in the past), but I actually ended up deleting it. I think composer does a better job picking the best release for you and blindly relying on the latest release probably isn't a good idea. 

Let me know  if you have a different suggestion or if you think the latest tag should come back.

Have a great day,
Fabrizio

**Comment by jhoelzl** [comment]
Hi @fbrnc, you are right, it is better to remove the "latest release" tag.
