### ISSUE TITLE
Mageworx SEO Cron Errors, Please Help

### ISSUE THREAD

**Issue by michigandata** [AOEpeople/Aoe_Scheduler#144]
We checked this and the method "scheduledForCdGenerateTemplates" exists. Please contact the developer of the AOEScheduler
--------------Error-----------------------------------
    Error while running "mageworx_seoxtemplates_category_description_generate"
    "mageworx_seoxtemplates_category_description_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForCdGenerateTemplates does not exist' in /home//public_html/app/Mage.php:595
    Stack trace:
    #0 /home/detroit/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home//public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_category_meta_description_generate"
    "mageworx_seoxtemplates_category_meta_description_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForCmdGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_category_meta_keywords_generate"
    "mageworx_seoxtemplates_category_meta_keywords_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForCmkGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_category_meta_title_generate"
    "mageworx_seoxtemplates_category_meta_title_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForCmtGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_product_description_generate"
    "mageworx_seoxtemplates_product_description_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForPdGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_product_image_alt_generate"
    "mageworx_seoxtemplates_product_image_alt_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForPiaGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_product_meta_description_generate"
    "mageworx_seoxtemplates_product_meta_description_generate" messages:

    ---EXCEPTION---
    exception 'Mage_Core_Exception' with message 'Invalid callback: seoxtemplates/observer_cron::scheduledForPmdGenerateTemplates does not exist' in /home/public_html/app/Mage.php:595
    Stack trace:
    #0 /home/public_html/app/code/community/Aoe/Scheduler/Helper/Data.php(297): Mage::throwException('Invalid callbac...')
    #1 /home/public_html/app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('seoxtemplates/o...')
    #2 /home/public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()
    #3 /home/public_html/app/code/community/Aoe/Scheduler/controllers/Adminhtml/CronController.php(89): Aoe_Scheduler_Model_Schedule->runNow(false)
    #4 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Aoe_Scheduler_Adminhtml_CronController->runNowAction()
    #5 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('runNow')
    #6 /home/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #7 /home/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #8 /home/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #9 /home/public_html/index.php(83): Mage::run('', 'store')
    #10 {main}

    Error while running "mageworx_seoxtemplates_product_meta_keywords_generate"
    "mageworx_seoxtemplates_product_meta_keywords_generate" messages:

**Comment by fbrnc** [comment]
If these methods ```seoxtemplates/observer_cron::*``` actually all exist in the code then it looks like the modules isn't installed correctly. 
I don't think this is an Aoe_Scheduler issue, since Aoe_Scheduler is only trying to execute a callback provided by the module. 
Can you double check if the module is installed correctly and all the files are in the right place?

**Comment by LeeSaferite** [comment]
Looking at the helper, it seems like `Mage::getModel('seoxtemplates/observer_cron')` is failing to return the model. This would seem to indicate a problem with the install of your other module.

**Comment by michigandata** [comment]
Thank you I have sent this to development for review.

**Comment by michigandata** [comment]
Finally the acknowledged the problem in the coding :)
Let me explain what the problem was and how we fixed it. For some reason the extension AOE_Scheduler tried to call the model "seoxtemplates/observer_cron" but not the correct model "mageworx_seoxtemplates/observer_cron". We could not find a reason of this. We just added a support of the model "seoxtemplates/observer_cron" to our extension to make everything working fine.

**Comment by michaellehmkuhl** [comment]
@michigandata: We ran into this same issue. It was due to a bug in the MageWorx SEO Suite extension code. Their cron definition in the config.xml was set to "seoxtemplates/observer_cron" rather than "mageworx_seoxtemplates/observer_cron". This was fixed in v4.1.1 of the extension. http://www.mageworx.com/seo-suite-ultimate-magento-extension.html#changelog

**Comment by LeeSaferite** [comment]
Closing since this is not a problem in the scheduler module.
