### ISSUE TITLE
Time off by several hours after virtual machine restore

### ISSUE THREAD

**Issue by srmobile** [AOEpeople/Aoe_Scheduler#145]
Where does this module get its date and time from?

After restoring my site that is on a VM, the AOE Schedule has the date and time from when the machine snapshot was taken.

Server time is correct, Magento Date and Time are correct.

Any ideas?

Thank you

SR

**Comment by fbrnc** [comment]
Doesn't sound like a Scheduler issue to me, since the Scheduler uses the time provided by Magento and that's the PHP time. 

Never experienced this problem with Vagrant/Virtualbox.

**Comment by fbrnc** [comment]
Hi @srmobile, closing this issue for now. Feel free to reopen if you're still experiencing this and/or have some more information how this could be related to Aoe_Scheduler.
