### ISSUE TITLE
Died jobs does not get cleaned

### ISSUE THREAD

**Issue by fcorriga** [AOEpeople/Aoe_Scheduler#146]
Died jobs does not get cleaned, resulting in a very long timeline that can be only cleaned in List view by selecting and deleting Died jobs.

Ideally there should be a parameter to set in the config to set the Timeout of those jobs OR at least the Failure History Timeout should be kept into consideration.

**Comment by fbrnc** [comment]
Thanks for reporting this @fcorriga. You're totally right. I introduced this new state (and two more) and forget about them in the cleanup method.
