### ISSUE TITLE
"Died" filter does not work

### ISSUE THREAD

**Issue by fcorriga** [AOEpeople/Aoe_Scheduler#147]
"Died" jobs filter does not work in List view.

**Comment by steverobbins** [comment]
Which version do you have installed?  There was a related issue #138 not too long ago that has since been fixed.

**Comment by fcorriga** [comment]
i'll update and report back

**Comment by fcorriga** [comment]
Updated to the latest master.
I will wait for a died job and see if it fixes

**Comment by fcorriga** [comment]
Ok, it works.
