### ISSUE TITLE
Lock identifiers in scheduler_cron.php might be wrong

### ISSUE THREAD

**Issue by Caprico85** [AOEpeople/Aoe_Scheduler#148]
We have a custom cronjob that tends to run up to ~20 minutes. I tried to separate it into another cron group so it will not block other cronjobs while running. I added it to the group "group2" and edited my /etc/crontab as follows:
```
* * * * * www-data /bin/bash /var/www/shop/scheduler_cron.sh --mode default --excludeGroups group2
* * * * * www-data /bin/bash /var/www/shop/scheduler_cron.sh --mode default --includeGroups group2
```

In scheduler_cron.php the identifiers are created as follows:
```IDENTIFIER=$(echo -n "${MODE}${INCLUDE_GROUPS}${EXCLUDE_GROUPS}${INCLUDE_JOBS}${EXCLUDE_JOBS}" | "${MD5SUM_BIN}" - | cut -f1 -d' ')```

As there are no separators between the variables both commands will create the identifier "defaultgroup2" (without md5). So both commands use the same lockfile and still keep each other from running.

 

I added separators between the variables. Now both commands have different identifiers (`"default||group2||"` vs. `"default|group2|||"`) and now everything works:

```IDENTIFIER=$(echo -n "${MODE}|${INCLUDE_GROUPS}|${EXCLUDE_GROUPS}|${INCLUDE_JOBS}|${EXCLUDE_JOBS}" | "${MD5SUM_BIN}" - | cut -f1 -d' ')```

**Comment by LeeSaferite** [comment]
You are correct, thanks!

Will you submit a pull request?
