### ISSUE TITLE
When is it compatible with magento 1.9.2.1

### ISSUE THREAD

**Issue by Feggel** [AOEpeople/Aoe_Scheduler#160]
Hi,
When will Magento 1.9.2.1 be supported. I have it installed, but it isn't working.
It doesn't show up in the backend under /system.

Love the extension!

**Comment by sasoriza** [comment]
Working fine for me on 1.9.2.1...

**Comment by robbieaverill** [comment]
Works fine for me too running EE 1.14.2.1 (same CE version as 1.9.2.1)

**Comment by fbrnc** [comment]
@Feggel: Closing this issue. Feel free to reopen if you think there's an issue.
