### ISSUE TITLE
Notice: Undefined variable: maxAge

### ISSUE THREAD

**Issue by gbillingsley** [AOEpeople/Aoe_Scheduler#161]
I'm getting the following notice in system.log:

ERR (3): Notice: Undefined variable: maxAge  in ...app/code/community/Aoe/Scheduler/Model/ProcessManager.php on line 118

This notice is getting logged several times per minute in the first few seconds of that minute, so I believe it is getting thrown every time a cron job is being run.

**Comment by steverobbins** [comment]
Curious, what is the value of this configuration on your install?

![image](https://i.imgur.com/EkD6UCg.png)

**Comment by gbillingsley** [comment]
That's it. The variable is blank in my configuration. I set it to 15 and the notice stopped.

From a module/programming standpoint, the $maxAge variable should probably be checked before being used as an argument for a function.

Thanks for the help.
