### ISSUE TITLE
No heartbeat task found. Check if cron is configured correctly.

### ISSUE THREAD

**Issue by ADDISON74** [AOEpeople/Aoe_Scheduler#165]
This is a must have extension since all emails have to be send using cron jobs. I appreciate for your work.

AOE is working fine, but I have trouble with an error message if I do an action. I am using Magento 1.9.2.1 and AOE latest from Git .

Here are the steps to reproduce it:

Go to System -. Scheduler -> List View. Here you can see my admin interface with no errors. "Scheduler is working. (see Last heart beat: 0 minute(s) ago)"

![aoe_1](https://cloud.githubusercontent.com/assets/8360474/9836316/cce4487a-5a1d-11e5-9f39-6b4917c0e4fb.jpg)

Now select All then from Actions choose Delete and click [Submit] button. Here is the screenshot after page reloads. There is an error message "No heartbeat task found. Check if cron is configured correctly.". 

![aoe_2](https://cloud.githubusercontent.com/assets/8360474/9836356/08dd3840-5a1f-11e5-885b-19563ce81b97.jpg)

Click on [Generate Scheduler] button. You will get again a full list of tasks. Error message is still there. If you clean Magento cache the error message is gone (sometimes you need to refresh the page). Why is this happening? Did I do something wrong or is an issues related to your extension?

Thank you.

**Comment by ADDISON74** [comment]
Well I tested other way without clearing Magento cache. 

After deleting the list and generating a new one, I waited for 2 minutes and refresh the "Scheduled tasks" page. Now there is no error message. It shows "Scheduler is working (Last heart beat: 1 minute(s) ago). I guess that error message is normal for a period of time, am I right? In this case page must be refreshed after that period to get rid off the error message.

**Comment by fbrnc** [comment]
Hi @ADDISON74,

yes you're right. This is expected behavior. The heartbeat detection is done by checking if the last heartbeat task was run within the last 5 min. If you delete all schedules you also end up deleting the history of all the heartbeat tasks and for the next couple of minutes Aoe_Scheduler believes that cron isn't set up properly since it never have seen any heartbeat tasks.

**Comment by SergioDuclos** [comment]
Instalei seu modulo de agendamento, tudo funcionando, somente o newsletter, que não enviar, é necessário fazer alguma configuração adicional

Sergio Duclos
www.duclos.com.br
DUCLOS Webstore  for Developers

**Comment by paraskumarmd** [comment]
![magento admin](https://cloud.githubusercontent.com/assets/17145051/12921941/800e3e98-cf75-11e5-820c-e01ae112bfff.png)

kindly let me know what to do in this case. i had installed a shipping order management extention earlier is that creating a conflict? i have disabled it from the shipping methods, however, it still shown under the sales tab of the magento admin panel menu.

is there any issue in the following config?

![configuration system magento admin2](https://cloud.githubusercontent.com/assets/17145051/12922091/1d393c0e-cf76-11e5-9291-b4f5ec0e7dfd.png)

**Comment by Iddu** [comment]
Hi all,
I'm having the same problem here "No heartbeat task found. Check if cron is configured correctly".
This happened the moment i upgraded from V1.9.0.1 to V1.9.2.3.
I have installed as well the latest AOL scheduler.
I can't get the cron jobs to work automatically, if I run them manually there are no errors/problems.
What I noticed is that in the "Cron (Scheduled Tasks) - all the times are in minutes" section, the "Enable Scheduler" drop down menu is simply missing. Could that be the problem?

Any suggestions? Thanks!

![image](https://cloud.githubusercontent.com/assets/17148668/12942704/5196a6aa-cfdd-11e5-8fe8-f621ea868d70.png)

**Comment by paraskumarmd** [comment]
I am using Version 1.9.2.0 of Magento for my website. only the order emails are not triggered. and even if i go to the orders menu and click send button the order email is not sent but i get the message the email is sent.

But if i go to the invoice section and then click on the send button the invoice mail is sent. To the respective email ids!

**Comment by Iddu** [comment]
I believe I managed to sort the problem out (error -> No heartbeat task found. Check if cron is configured correctly.).

I have removed in .htaccess this whole code block. Since then it all works fine!

![image](https://cloud.githubusercontent.com/assets/17148668/12949811/350b6228-d00a-11e5-941a-9632d9775abd.png)

**Comment by paraskumarmd** [comment]
ok friend i will try this out....if it works many thanks for the help!

**Comment by hostep** [comment]
Guys, please don't do this, this was an extra security measure which the Magento team added in security patch SUPEE-6788, if you search for `APPSEC-1037` on [this page](https://magento.com/security/patches/supee-6788) you'll see what this is about.

So you should never call the cron.php file using `wget` or `curl` or something like that which triggers the Apache webserver to call the cron.php file (this is what the .htaccess file is blocking intentionally)

Just follow the [instructions](https://github.com/AOEpeople/Aoe_Scheduler/blob/master/doc/instructions.md) to properly set up your cron.

**Comment by brandontamm** [comment]
@hostep - FYI - The link you posted to the instructions page has a dead link in the middle of the page

**Comment by baby-in-magento** [comment]
Even i am also facing problem of Last heartbeat is older than one hour. But i double checked it, cron is working fine. I downloaded latest version here : https://github.com/AOEpeople/Aoe_Scheduler/archive/v1.3.1.zip please help me to find solution.

**Comment by baby-in-magento** [comment]
I deleted all scheduled tasks, than generated,  than cleared cache, refreshed page, still i am getting : No heartbeat task found. Check if cron is configured correctly.

**Comment by ledian-hymetllari** [comment]
In my case , Configured cron to run 'scheduler_cron.sh' , after that cleared cache and it worked.
