### ISSUE TITLE
Change search Job from option list to input text box

### ISSUE THREAD

**Issue by ADDISON74** [AOEpeople/Aoe_Scheduler#166]
In "Scheduled tasks" page I would like to get rid off job lists and switch to an input text box. Why I am doing this? Because I would like to watch more than one job, let's say two jobs: 

- core_email_queue_clean_up
- core_email_queue_send_all

As it is now it only allows one job for search. With an input text box you can search core_email_queue to get the two above.

Thank you.

![job_filter](https://cloud.githubusercontent.com/assets/8360474/9836493/0c03e39c-5a25-11e5-9615-7737bbbbe884.jpg)

**Comment by ADDISON74** [comment]
This is not an issue it is feature request.

**Comment by ADDISON74** [comment]
I just downloaded the latest version and this feature is not available yet. Still same old behavior. I cannot filtering jobs by input text.

**Comment by fbrnc** [comment]
Hi @ADDISON74,
the default behavior is still the old one. If you want to switch to a simple text field you have to change following setting to "Text":

```
System > Configuration > System > Cron > Job code filter type in list view
```

**Comment by ADDISON74** [comment]
yes, I will. your option makes sense. thank you for your nice support. 

p.s. your extension should be integrated into Magento default. my opinion ...
