### ISSUE TITLE
Force User

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#189]
Running cron as a different user than the web user can result in problem when files are being created or accessed. 
That's why I'd like to introduce a new feature that helps preventing this.
A new configuration value "force_user" (or so) allows to configure the user that's expected to run cron (e.g. "www-data").
Then everytime cron is being executed it will check if it is the correct user and prevent execution if users don't match.
Since people might not want to deal with this leaving the field blank should (which will be the default value) will workaround the check.
Also there should probably be a message in the scheduler backend modules (that can be suppressed in configuration) if this value hasn't been configured.

**Comment by robbieaverill** [comment]
Do you check this against the user running Magento, or use a setting in admin to specify the user?

**Comment by fbrnc** [comment]
I haven't implemented this yet, but I'm planning on introducing a configuration value that the user has to fill out (of course I can suggest the current user there).
Since I think it's important to "protect" the user from running manually running crons on the command line or from misconfiguring cron I'd like to introduce a warning on the Scheduler admin modules that suggests to use this feature in case the value is empty (of course there should be a configuration option to hide this warning in case you really want to keep it empty).

**Comment by robbieaverill** [comment]
Sounds good - summary of required changes (?):

* Add configuration value for the user that the cron should be run as (no default value). Give it a label that suggests you enter the user currently running Magento
* Implement a check (observer or controller `preDispatch(?)`) in the Scheduler section of Magento admin to check that the user setting is set:
  * If not, display a warning message suggesting it be set
  * If it is set, but is a different user to that running Magento, display a different warning message
  * Do you implement the same check when running from the command line?
* Add configuration value for whether or not to show the warning messages (default `true`)

I can help out with this if you'd like.

Cheers,
Robbie

**Comment by fbrnc** [comment]
Hi @robbieaverill,

if you want to contribute this feature: knock yourself out! That would be awesome.

I would suggest adding the check somewhere inside `Aoe_Scheduler_Model_Schedule->runNow` so that we can capture a wrong user in every scenarios. (That method is way too long and should be refactored, but that should go into a different issue).

In addition to that I'd add somethind to `Aoe_Scheduler_Controller_AbstractController->indexAction` that checks for the value being configured and offers you links inside the message for "hide this message" and "use <fillInCurrent User>"

**Comment by robbieaverill** [comment]
Hey Fabrizio,

Happy to. Give me a few days to schedule in some time.

Cheers,
Robbie

On Tuesday, 10 November 2015, Fabrizio Branca <notifications@github.com>
wrote:

> Hi @robbieaverill <https://github.com/robbieaverill>,
>
> if you want to contribute this feature: knock yourself out! That would be
> awesome.
>
> I would suggest adding the check somewhere inside
> Aoe_Scheduler_Model_Schedule->runNow so that we can capture a wrong user
> in every scenarios. (That method is way too long and should be refactored,
> but that should go into a different issue).
>
> In addition to that I'd add somethind to
> Aoe_Scheduler_Controller_AbstractController->indexAction that checks for
> the value being configured and offers you links inside the message for
> "hide this message" and "use "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AOEpeople/Aoe_Scheduler/issues/189#issuecomment-155153789>
> .
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by fbrnc** [comment]
Ok, I'll assign this ticket to you (no pressure).
Feel free to un-assign yourself at any point in time :)

**Comment by fbrnc** [comment]
Ok, looks like I can't assign anybody who's not part of the AOE team. However, feel free to work on this whenever you want.

Thanks,
Fabrizio

**Comment by robbieaverill** [comment]
What do you think the best way to determine which user the cron is running as would be? One option is to scan the specified user's crontab to see if the definition is in place for it..

**Comment by robbieaverill** [comment]
Adding requirement from #60 for configuration for warn/kill of configuration is set but doesn't match.

**Comment by robbieaverill** [comment]
I think I'll run the check if there is a job running at the time, and track the user who last ran a job

**Comment by robbieaverill** [comment]
Hey @fbrnc,

By the way - what I meant above is for when the admin controllers are trying to detect if processes are running as the wrong user, the best way to do it. We could either hope that one is currently running and look up its user, we could track the user that runs every process (lots of extra and probably identical data) or we could use a config variable each time a process runs to track the user that ran it.

No problem for when you run it via the CLI as we can check at the time.

I might also suggest that the "force" flag may override the default for warn/kill if presented?

It's coming along nicely.

Cheers,
Robbie

**Comment by robbieaverill** [comment]
Hey Fabrizio,

Suggest this issue be closed now since the PR #200 has been merged?

Cheers,
Robbie
