### ISSUE TITLE
Fix Travis builds

### ISSUE THREAD

**Issue by robbieaverill** [AOEpeople/Aoe_Scheduler#192]
The Travis history shows that the CI builds have been broken for a while.

Task logged to fix them and provide a stable platform going forwards.

**Comment by robbieaverill** [comment]
Possible that all is needed is to change the `magento-ce` prefix to `magento-mirror` to allow Magerun to install the version now that the original package URLs are dead?

**Comment by fbrnc** [comment]
Updated the Travis File (and included 1.9.2.2): 643da04d1c2da94f782d65d84c785be1c0ceaca3 
Let's see what happens..

**Comment by robbieaverill** [comment]
Seems legit.

**Comment by fbrnc** [comment]
The builds seems to be working agian. At least one of the testcases isn't very stable. I'll have to look into that. (And really we should be having more testcases anyway... :)

**Comment by robbieaverill** [comment]
Nice one - might be related to the ones mentioned in #191
