### ISSUE TITLE
Not finding PHP binary location and not finding gethostname()

### ISSUE THREAD

**Issue by gnickoloff** [AOEpeople/Aoe_Scheduler#193]
Had to make small edits in scheduler_cron.php

@ ~ ln. 80 had to set path to PHP binary explicitly instead of using value from "which php":
    `PHP_BIN="/usr/local/php5/bin/php"`
   ` #PHP_BIN=$(which php || true)`

And replace `gethostname()` with actual host name in Schedule.php and ProcessManager.php in various places to get it to run.

After those changes, all is well.

Most likely not actually a "bug" as this is due to some kind of weirdness in how my server is configured, but wasn't an issue before the update... thought someone might want to know about it, etc. and don't do Twitter. Feel free to delete/berate, etc.

**Comment by fbrnc** [comment]
Thanks for the note! In the long run we might remove the wrapping shell script so this problem will be obsolete. But until then it might be useful information for other facing the same issue. 
Thank you,
Fabrizio
