### ISSUE TITLE
Run Now option in Cron Schedule Disappeared. 

### ISSUE THREAD

**Issue by sirlasc** [AOEpeople/Aoe_Scheduler#203]
Suddenly Run Now is not longer an option. Could you help us?

We are running the latest version with magento 1.9.0.1

**Comment by steverobbins** [comment]
This feature is [disabled by default now](https://github.com/AOEpeople/Aoe_Scheduler/blob/master/app/code/community/Aoe/Scheduler/etc/config.xml#L162) but can be re-enabled in your system configuration.

**Comment by sirlasc** [comment]
Steve we were crushing our heads trying to find out why this broke :)

Where exactly can we re-enable it?

**Comment by LeeSaferite** [comment]
System > Configuration > Advanced > System > Cron > Enable "run now"
