### ISSUE TITLE
Abstract.php

### ISSUE THREAD

**Issue by darklinki** [AOEpeople/Aoe_Scheduler#212]

**Comment by darklinki** [comment]
Got the problem if I run the scheduler I get the following error:

<b>Fatal error</b>:  require_once(): Failed opening required '/abstract.php' (include_path='.:/usr/lib/php5.5') in <b>/homepages/xx/xxxx/htdocs/src/shell/scheduler.php</b> on line <b>3</b><br />


The crontab is configured like given in the configuration on magento.

**Comment by fbrnc** [comment]
This has already been fixed in 5cc0cb49e2769fbd64688f859e4c6cd94f1ab29a
Let me know if you still experience this problem after updating to the latest revision.
