### ISSUE TITLE
Cannot filter List View by "running"

### ISSUE THREAD

**Issue by colinmollenhour** [AOEpeople/Aoe_Scheduler#214]
If there is not a job running at the time the list view page is loaded then "running" will not be an option in the Status column filter. The getStatuses method should return a static array rather than loading the statuses dynamically.

**Comment by fbrnc** [comment]
Good Point! Just added that.

**Comment by colinmollenhour** [comment]
Neat trick with using reflection to get the statuses... Thanks for the quick fix!
