### ISSUE TITLE
Instruction Tab shell_exec() error

### ISSUE THREAD

**Issue by darekkos** [AOEpeople/Aoe_Scheduler#225]
Hi,
I am getting the following error when trying to access System->Scheduler->Instruction tab:

Warning: shell_exec() has been disabled for security reasons  in /var/www/vhosts/shipton.com/httpdocs/app/code/community/Aoe/Scheduler/Block/Adminhtml/Instructions.php on line 13

What could be the cause of that?

We are running Magento 1.9.0.1 

Thank you

Darek

**Comment by thebigben** [comment]
Looks like your hoster disabled the shell_exec function because its mostly used in Evil PHP Shells/Backdoors, ask your hoster to enable it or wait for @AOEpeople to maybe find a way without shell_exec...

**Comment by thebigben** [comment]
It looks like you can Patch it yourself
Search for 
return trim(shell_exec('whoami'));
should be in
app/code/community/Aoe/Scheduler/Block/Adminhtml/Instructions.php
&
app/code/community/Aoe/Scheduler/Helper/Data.php

And hardcore return your executive user

dev/tests/aoe_scheduler/AbstractTest.php
also uses shell_exec but it looks like its some kind of Test maybe a Test for the Build Bot

**Comment by darekkos** [comment]
Hi thebigben,
Thanks a lot for helping out!
This is what I have done in Instructions.php and it seems to work fine now, do you think that is acceptable or there is a better way to do it?
 public function getCurrentUser()
    {
        //return trim(shell_exec('whoami'));
            return trim(get_current_user());
    }

**Comment by thebigben** [comment]
That would work out, but as far as I know it would return the owner of the file as owner will be same as executer(Source: PHP.net on get_current_user()) 

$processUser = posix_getpwuid(posix_geteuid());

**Comment by darekkos** [comment]
Thanks a lot (again), you've been of great help!
Regards,
Darek
