### ISSUE TITLE
Cant access any settings, or views

### ISSUE THREAD

**Issue by seansan** [AOEpeople/Aoe_Scheduler#23]
Problem 1) For every option belonging to the Aoe menu I only get a text stating:
Scheduler is working. (Last execution: 0 minute(s) ago)

I can access the config, cant access the timeline etc. So when the hearthbeat is too old: I cant access any options, and when it is youger than 5 minutes I cant access any options

Problem 2) Also we see many messages in th elogs with "exception 'Mage_Core_Exception' with message 'Too late for the schedule.'"

(also mentioned on your site)

Many thanks!!

**Comment by fbrnc** [comment]
Version 1 is out and solves these problems.
