### ISSUE TITLE
Error after SUPEE-7405 patch

### ISSUE THREAD

**Issue by alxblog** [AOEpeople/Aoe_Scheduler#230]
Hi,

After applying the last SUPEE-7405 Patch on Magento 1.9.2.1, I receive CRON Error notification Mail 

> Cron error while executing captcha_delete_expired_images:
> 
> exception 'Exception' with message 'Unable to create directory '/home/WEBSITE/www/media/captcha'. Access forbidden.' in /home/WEBSITE/www/lib/Varien/Io/File.php:628
> Stack trace :
> # 0 /home/WEBSITE/www/lib/Varien/Io/File.php(625): Varien_Io_File->checkAndCreateFolder('/home/itisbijou...', 493)
> # 1 /home/WEBSITE/www/app/code/core/Mage/Captcha/Helper/Data.php(123): Varien_Io_File->checkAndCreateFolder('/home/itisbijou...', 493)
> # 2 /home/WEBSITE/www/app/code/core/Mage/Captcha/Model/Observer.php(256): Mage_Captcha_Helper_Data->getImgDir(Object(Mage_Core_Model_Website))
> # 3 [internal function]: Mage_Captcha_Model_Observer->deleteExpiredImages(Object(Aoe_Scheduler_Model_Schedule))
> # 4 /home/WEBSITE/www/app/code/community/Aoe/Scheduler/Model/Observer.php(79): call_user_func_array(Array, Array)
> # 5 /home/WEBSITE/www/app/code/core/Mage/Core/Model/App.php(1357): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
> # 6 /home/WEBSITE/www/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
> # 7 /home/WEBSITE/www/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
> # 8 /home/WEBSITE/www/cron.php(77): Mage::dispatchEvent('default')
> # 9 {main}

Any idea ?

Best Regards,

Alex

**Comment by s-hoffman** [comment]
Hi @alxblog,

It seems that the default file permissions may have changed preventing the cronjob from creating a directory.
You are getting an error, I suspect that the the permissions on media were changed.
/home/WEBSITE/www/media/captcha.

Also possible is that captcha exists, and is not a directory.
