### ISSUE TITLE
shell command whoami not found

### ISSUE THREAD

**Issue by hanuman42** [AOEpeople/Aoe_Scheduler#238]
I am using Aoe_Scheduler with a fresh Magento 1.9.2.3 in a shared hosting environment.
Your extension works but I am having this issue:

My Hoster does not provide me with the shell command whoami.

Aoe_Scheduler does not get the username, that is executing the cron but still works.
app/code/community/Aoe/Scheduler/Block/Adminhtml/Instructions.php
app/code/community/Aoe/Scheduler/Helper/Data.php

Can I simply comment this line out?
`return trim(shell_exec('whoami'));`
and do this?
`return ('');`

edit:
well, obviously I can, but are there any bad things happening because Aoe_Scheduler cannot see which user is executing the cron?

thank you and greetings

**Comment by robbieaverill** [comment]
Hi @hanuman42 

What kind of environment are you running this on?

For a short term fix you can disable the "Show cron user message" setting in the scheduler configuration. It's there as a safeguard, but it's important that your scheduler runs rather than throwing this error.

R

**Comment by hanuman42** [comment]
thanks for your answer...
so, I leave it and just don't use the shell_exec('whoami');

**Comment by sprankhub** [comment]
I also has issues, because `whoami` was disabled by the hosting provider (Mittwald).

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/0303df69dcac271c45b9aa0b5869ff884141d790
