### ISSUE TITLE
v1.3.1 shell syntax error in Magento 1.9.2.4

### ISSUE THREAD

**Issue by dermatz** [AOEpeople/Aoe_Scheduler#247]
Hi all,

i install the Scheduler 1.3.1 with composer install into my magento 1.9.2.4.
If i run `sh scheduler_cron.sh` i get 
`-Powered-By: PHP/4.4.9
Content-type: text/html
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in <b>/homepages/xxx/xxx/xxx/xxx/xxx/shell/scheduler.php</b> on line <b>12</b><br />`

of course, so i did not get a heartbeat 

any ideas ?

best regards :)

**Comment by fbrnc** [comment]
Are you running Magento on PHP 4.4.9? If so I think this is the reason (also I doubt that Magento is running fine, unless you're running a different version in your webserver. Can you check what version you're running by typing `php -v` in your command-line?

**Comment by dermatz** [comment]
Hi Fabrizio,

the shell is running in PHP 5.2.17 (cgi-fcgi) and the website in php 5.6.
Its a shared host atm.

**Comment by dermatz** [comment]
Oh you are right. 
php was running with 5.2 in command line as fast-cgi.   .. 

now i start it so and all is fine:   
`$ php5.5-cli shell/scheduler.php`

thanks fabrizio
