### ISSUE TITLE
PHP Fatal error:  Call to undefined function posix_kill() 

### ISSUE THREAD

**Issue by ZayLong** [AOEpeople/Aoe_Scheduler#256]
This error returns every morning around 2AM

**PHP Fatal error:  Call to undefined function posix_kill() in /mnt/magento/app/code/community/Aoe/Scheduler/Model/Schedule.php on line 440**

I did a bit of research and came to the conclusion that posix wasn't installed, so I downloaded the package but I still get this error.

Are there any solutions or any advice that could point me in the right direction towards resolving this error?

Thanks.

**Comment by shirtsofholl** [comment]
we have the same error
