### ISSUE TITLE
Add tag for 1.4.0

### ISSUE THREAD

**Issue by avoelkl** [AOEpeople/Aoe_Scheduler#257]
According to the [changelog](https://github.com/AOEpeople/Aoe_Scheduler/blob/master/changelog.md#version-140) the latest version is 1.4.0. I did not see a tag for this specific version. Can anyone of the maintainers add this one please? :) Thanks!

**Comment by peterjaap** [comment]
@fbrnc maybe?

**Comment by LeeSaferite** [comment]
Sorry everyone. We've been super super busy lately and haven't been able to do some of these maint tasks like we should. I have tagged v1.4.0 for you @avoelkl. Thank you for bringing up the issue.

**Comment by avoelkl** [comment]
Thanks, @LeeSaferite! :)
