### ISSUE TITLE
Add contab -e

### ISSUE THREAD

**Issue by michel1986** [AOEpeople/Aoe_Scheduler#261]
hello Support,

I have install the exstension but need I also to add the code :
- \* \* \* \* ! test -e /data/web/public/maintenance.flag && /bin/bash /data/web/public/scheduler_cron.sh --mode always
- \* \* \* \* ! test -e /data/web/public/maintenance.flag && /bin/bash /data/web/public/scheduler_cron.sh --mode default

To my Crontab ?

I have now add the follow things:
*/5 \* \* \* \* flock -n ~/.cron.lock php /data/web/public/cron.php

**Comment by tmotyl** [comment]
please read documentation https://github.com/AOEpeople/Aoe_Scheduler/blob/master/doc/instructions.md
