### ISSUE TITLE
get rid of shell_exec()

### ISSUE THREAD

**Issue by ghost** [AOEpeople/Aoe_Scheduler#263]
```
root@mbp:/app/code/community/Aoe# grep -srl "shell_exec"
Scheduler/Test/Model/Schedule/Scheduling.php
Scheduler/Block/Adminhtml/Instructions.php
```

Honestly I have a bad feeling in my stomach when having shell_exec() enabled with php..

Can we get rid of those shell_exec() stuff?  Patch following...

Replacing shell_exec('whoami') with get_current_user() for example..

Thanks

**Comment by LeeSaferite** [comment]
While I 100% agree with you, it's a bit ironic that the standard cron runner uses shell_exec as a core feature and will not work with the function.

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/cron.php#L66-L67

**Comment by LeeSaferite** [comment]
Also, get_current_user is 100% useless in this case as it returns the script owner not the process owner.

**Comment by LeeSaferite** [comment]
What we would need is

    posix_getpwuid(posix_geteuid())

**Comment by robbieaverill** [comment]
Would fix #238

**Comment by robbieaverill** [comment]
Pull request submitted for #238 which removes the `shell_exec` use in the instructions block and the helper. The tests will still use it, and I'd love to see them mocked one day :)

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/0303df69dcac271c45b9aa0b5869ff884141d790
