### ISSUE TITLE
Scheduler Magento 1.9.2.4 PHP 5.5 not working 

### ISSUE THREAD

**Issue by visenco** [AOEpeople/Aoe_Scheduler#276]
I am not getting the Scheduler working, when I add the commands suggested:

sudo crontab -u myserver -e
- \* \* \* \* ! test -e /home/myserver/domains/asianfoodmarket.nl/public_html/maintenance.flag && /bin/bash /home/myserver/domains/asianfoodmarket.nl/public_html/scheduler_cron.sh --mode always
- \* \* \* \* ! test -e /home/myserver/domains/asianfoodmarket.nl/public_html/maintenance.flag && /bin/bash /home/myserver/domains/asianfoodmarket.nl/public_html/scheduler_cron.sh --mode default

In direct admin I am getting errors
Error Creating Cron Job

Details

crontab returned non zero value: "./data/users/myserver/crontab.conf.tmp":3: bad command errors in crontab file, can't install. 

After a refresh they are showing (both the always and the default

What do I do wrong ?

**Comment by LeeSaferite** [comment]
It looks like your time string has only 4 entries instead of the required 5. Add one more * and see if that fixes it.

**Comment by visenco** [comment]
Sorry, no idea what you mean

**Comment by LeeSaferite** [comment]
I meant that this:
`* * * * ! test -e /home/myserver/domains/asianfoodmarket.nl/public_html/maintenance.flag && /bin/bash /home/myserver/domains/asianfoodmarket.nl/public_html/scheduler_cron.sh --mode always`

Should probaby be this:
`* * * * * ! test -e /home/myserver/domains/asianfoodmarket.nl/public_html/maintenance.flag && /bin/bash /home/myserver/domains/asianfoodmarket.nl/public_html/scheduler_cron.sh --mode always`

**Comment by visenco** [comment]
I did it with the extra *, but still the same. Do you want access ?

**Comment by LeeSaferite** [comment]
Not sure how to help you. I added the crontab line to a local machine and it was processed just fine. Perhaps contact your hosting provider for assistance with adding the crontab line.

**Comment by visenco** [comment]
They could not find it, should I delete the old .sh files ?

**Comment by visenco** [comment]
I am getting this as output in the mail: /bin/sh: sudo: command not found
