### ISSUE TITLE
No method named getRunModel() in Job.php even though it is called in getCallback()

### ISSUE THREAD

**Issue by djfordz** [AOEpeople/Aoe_Scheduler#295]
Hi,

You have a method that is being called in getCallback() in Job.php that tries to return $helper->getCallBack($this->getRunModel());  getRunModel() doesn't even exist in the program
![screenshot from 2016-08-22 10-25-43](https://cloud.githubusercontent.com/assets/5413221/17860354/dacf3244-6852-11e6-85a4-25463aca059a.png)
![screenshot from 2016-08-22 10-25-58](https://cloud.githubusercontent.com/assets/5413221/17860353/dacebcf6-6852-11e6-9ca6-768ef185fcdd.png)

. thus this is what we are getting on a customer store:

Cron error while executing xtento_orderexport_profile_1:

exception ‘Mage_Core_Exception’ with message ‘Invalid model/method definition, expecting "model/class::method".’ in /public_html/app/Mage.php:595 Stack trace: 
#0 app/code/community/Aoe/Scheduler/Helper/Data.php(294): Mage::throwException('Invalid model/m…') #1app/code/community/Aoe/Scheduler/Model/Job.php(143): Aoe_Scheduler_Helper_Data->getCallBack('')
#2 /public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(180): Aoe_Scheduler_Model_Job->getCallback()

 #3 public_html/app/code/community/Aoe/Scheduler/Model/Schedule.php(570): Aoe_Scheduler_Model_Schedule->runNow(true)
#4 /public_html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#5 public_html/app/code/local/Xtento/OrderExport/Model/Observer/Cron/Config.php(24): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#6 public_html/app/code/core/Mage/Core/Model/App.php(1338): Xtento_OrderExport_Model_Observer_Cron_Config->addCronjobsToConfig(Object(Varien_Event_Observer))

 #7 public_html/app/code/core/Mage/Core/Model/App.php(1311): Mage_Core_Model_App->_callObserverMethod(Object(Xtento_OrderExport_Model_Observer_Cron_Config), ‘addCronjobsToCo…’, Object(Varien_Event_Observer)) 
#8 public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#9 /public_html/shell/scheduler.php(356): Mage::dispatchEvent('default', Array)
#10 /home/afsupply/public_html/shell/scheduler.php(21): Aoe_Scheduler_Shell_Scheduler->cronAction()
#11 public_html/shell/scheduler.php(382): Aoe_Scheduler_Shell_Scheduler->run() #12 {main}

**Comment by seansan** [comment]
+1

Same issue here, would be great if solved

Thx! Love AOE Scheduler

**Comment by seansan** [comment]
For now? 

        if (method_exists($this, 'getRunModel')) {
			return $helper->getCallBack($this->getRunModel());
		} else {
			return false; // boolean?
		}

**Comment by fbrnc** [comment]
Hi,
the `getRunModel()` method actually doesn't exist and that's ok since it's a magic method. The problem here is that some Magento modules don't configure their cron jobs correctly by not configuring `run_model`. Without that Aoe_scheduler can't execute the job, so it's expected behavior that this isn't working.
This only happens with some selected cron jobs, right? Please try fixing their cron configuration.
Hope this helps.

Have a great day,
Fabrizio

**Comment by seansan** [comment]
thanks I understand

however you must know sometimes we have limited influence on others .... 

so a workaround, or at least the ability to stop receiving clogged error logs and emails about this would already be a lot of help

how about adding a quick check
of model exists, then continue
if not then skip and make 1 entry in log explaining what is wrong?

thx

**Comment by seansan** [comment]
What would one have to add the extension? I dont see RunModel or run_model variables on other cron .... and am trying to fix but dont know how/where to add what ;P (any tips appreciated)

**Comment by djfordz** [comment]
@fbrnc Thanks for the resolution. Seems to be extension devs that need to get on the ball.  should have thought about it being a magic method. Again, thank you for the explanation.
