### ISSUE TITLE
Error Trying to run Cron

### ISSUE THREAD

**Issue by daschenbrener** [AOEpeople/Aoe_Scheduler#299]
I have magento 1.9.2.2 running on a server with Cpanel interface. 
Centos 7
Php 5.5

I am trying to get this working under Cpanel but everytime i try to run  

/bin/bash /home/gymstar/public_html/scheduler_cron.sh --mode always

Now i also am using the command line that the "information" tab generates.

> - \* \* \* \* /bin/bash /home/gymstar/public_html/scheduler_cron.sh --mode always
> - \* \* \* \* /bin/bash /home/gymstar/public_html/scheduler_cron.sh --mode default

i get this error

> Content-type: text/html
> 
> Available actions:
>    --action listAllCodes
>    --action lastRun --code <code> [--secondsFromNow]   Get the timestamp of the last successful run >of a job for a given code
>    --action scheduleNow --code <code>  Schedule a job to be executed as soon as possible
>    --action runNow --code <code> [--tryLock] [--force]         Run a job directly
>    --action disableJob --code <code>           Disable job
>    --action enableJob --code <code>            Enable job
>    --action wait [--timout <timeout=60>]               Active wait until no schedules are running.
>    --action flushSchedules --mode (future|all)         Flush schedules.
>    --action listAllRunningSchedules
>    --action listGroups
>    --action killAll
>    --action watchdog
>    --action cron --mode (always|default) [--includeJobs <comma separated list of jobs>] [-->excludeJobs <comma separated list of jobs>] [--includeGroups <comma separated list of groups>] [->-excludeGroups <comma separated list of groups>]

its like its not seeing the actions that are being passed to it.

Any assitance to get this working ASAP would be great

**Comment by SamueleColombo** [comment]
Same error here.

**Comment by Quazz** [comment]
If possible, disable Cpanel Jailshell . I have not found a different solution for this.

**Comment by my-git-hub** [comment]
Looks like PATH variable is set somehow different in jailshelled cron environment. So I suppose different php binary is used.
You can ssh to your cPanel account and set PATH in your crontab.

So crontab should start like:
```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

Anyway I also had to apply this fix https://community.magento.com/t5/Technical-Issues/Cronjob-error-also-Heartbeat-not-found/m-p/23867/highlight/true#M2116

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/280609348f3fa2db47994cfa3a22cb36806cb41d 
now you can pass path to binary as a param
