### ISSUE TITLE
No valid configuration found for enterprise_import_export_log_clean

### ISSUE THREAD

**Issue by chernjie** [AOEpeople/Aoe_Scheduler#30]
Aoe Scheduler complains of the above message despite having valid configuration for the above cronjob.

```
Cron error while executing enterprise_import_export_log_clean:

exception 'Mage_Core_Exception' with message 'No valid configuration found.' in magento/app/Mage.php:594
Stack trace:
#0 magento/app/code/community/Aoe/Scheduler/Model/Observer.php(36): Mage::throwException('No valid config...')
#1 magento/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#2 magento/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#3 magento/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('default', Array)
#4 magento/cron.php(73): Mage::dispatchEvent('default')
#5 {main}
```

**Comment by mindsoul** [comment]
i have a similar issue with latest version AOE
Cron error while executing marketplace_cron:

exception 'Mage_Core_Exception' with message 'No valid configuration found.' in /.../home/.../..../html/app/Mage.php:595
Stack trace:
#0 /../home/../../html/app/code/community/Aoe/Scheduler/Model/Observer.php(36): Mage::throwException('No valid config...')
#1 ETC...
![cron-errors](https://cloud.githubusercontent.com/assets/5087758/10908775/d94af658-823c-11e5-8950-c58fd2d17824.png)

**Comment by LeeSaferite** [comment]
The error message hasn't been in the codebase since October 12th 2013
https://github.com/AOEpeople/Aoe_Scheduler/commit/b9e89241571d3068d3ea56cfc8e9b77d8eac58bc

I'm not sure that still qualifies as the 'latest version' anymore. Where did you get this version of the code?

**Comment by mindsoul** [comment]
i have downloaded from here version 1.2.2 isn't the latest?
magento 1.9.0.1 all security patch applied,
all crons are working but this that give the error, clear all the cache everything, the developer said something of AOE having problems with some orphans in core_config_data...  or cache (which i have cleared several times...) or extensions that are no more installed ... but i don't get it how all this could be connected..

**Comment by LeeSaferite** [comment]
That error message does not exist in 1.2.2 so you are not running the version you think you are running.

My guess is you still have VERY old code for schedule under app/code/local that was moved to app/code/community.

Check under /app/code/local/Aoe/Scheduler and if you find that directory then you need to remove it. The local codepool has priority over the community codepool so it will hide the community version of the code.

**Comment by mindsoul** [comment]
when i did the upgrade, i have downloaded the old version keep it in a parallel window, and delete every folder regarding AOE on the server, and then upload the new version 1.2.2 , i've flushed the cache ..
![screen shot 2015-11-03 at 18 34 38](https://cloud.githubusercontent.com/assets/5087758/10914124/ad70a376-8259-11e5-8c14-6783835443c4.png)
there is no trace of AOE in app/code/local/,  but there is a folder with the module with the issue

**Comment by mindsoul** [comment]
i have notice someting,

if i go and select manually the cron, go to action and select "schedule now" it's working, but the next cron programmed  will give an error, and here i don't understand. I repeat all, but all other crons have success label. This is the cron 

![cron-error](https://cloud.githubusercontent.com/assets/5087758/10914612/e83cd7c0-825b-11e5-8856-475fd04c98bb.png)

**Comment by mindsoul** [comment]
this error is still coming back and receive cron errors even if I DELETED the AOE ... all the folders...Where is this still coming from? Flush the cache.... is driving me crazy
Cron error while executing innobyte_emag_marketplace_cron:

exception 'Mage_Core_Exception' with message 'No valid configuration found.' in ../../../../..app/Mage.php:595
Stack trace:
#0 ../../../../..app/code/community/Aoe/Scheduler/Model/Observer.php(36): Mage::throwException('No valid config...')
#1 ../../../../..app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#2 ../../../../..app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#3 ../../../../..app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('default', Array)
#4 ../../../../..cron.php(87): Mage::dispatchEvent('default')
#5 {main}

**Comment by LeeSaferite** [comment]
Please wrap any stack trace like that is the code markers so GitHub doesn't auto-link your stack trace to old issues.

So, looking at the stack trace you have not deleted the Aoe_Scheduler module as the stack trace has one of the Aoe_Scheduler files listed.

My suggestion would be fully remove the Aoe_Scheduler module, clear your caches, ensure it is fully removed, THEN re-install the latest release version which is [v1.2.2](https://github.com/AOEpeople/Aoe_Scheduler/releases/tag/v1.2.2) as of this post.

**Comment by mindsoul** [comment]
ok, i want to uninstall AOE completely, but it seams impossible, i delete every reference from core_config_data, cron_schedule, every file regarding, i install another module for schedule monitoring and i keep seeing **565043	aoescheduler_heartbeat	 	06.11.2015 22:20:09	06.11.2015 22:35:00**	 	 	 where is the system taking this jobs if i deleted everything, i even search through the project for AOE...or aoescheduler_heartbeat, no trace of it. So where is located this in magento database? why is the job **aoescheduler_heartbeat** still working if i've deleted every folder and file regarding AOE...?

**Comment by fbrnc** [comment]
Hi @mindsoul,
tasks are being stores in the `cron_schedule` table. You can safely truncate this table and let the default Magento schedule re-schedule all jobs (assuming you have cron configured correctly)
`truncate cron_schedule;`

I also assume you've missed a couple of files. Try running `find . -iname '*aoe*'` in your project root directory to get all files and directories that have AOE in their name.

**Comment by mindsoul** [comment]
Thank you Fabrizio, i couldn't find any trace of aoe, but i think i found the issue, we move the store from USA location to Europe location, on the same hosting company, so we keep the same hosting provider. I figure out about the problem when i check the raw source of email and saw that the cron error, was send from an old ip and service, then i realise that there ware still an active cron, and the old aoe module was still in use. How was this connected with the new ip, new service, and db have no idea..., the hosting made all the move all the data and services... thank's again for your support. Best regards.
