### ISSUE TITLE
Enterprise Page Cache Crawler Running Forever, Breaking Cron

### ISSUE THREAD

**Issue by brandontamm** [AOEpeople/Aoe_Scheduler#304]
I am not sure why the page cache crawler is running so long, but how can I:
1. Stop the task
2. Troubleshoot why it is hanging

I noticed the issue after adding 700 categories to the product catalog. Too much for the page cache crawler? Any suggestions to avoid this? The long running task breaks all my other cron jobs

**Comment by brandontamm** [comment]
![screen shot 2016-10-25 at 9 29 49 am](https://cloud.githubusercontent.com/assets/1854016/19690317/f96966b4-9a95-11e6-8b9b-7fe54553239e.png)

**Comment by brandontamm** [comment]
I stopped the process using "kill -9 <pid> for the process running the: /var/www/html/web/scheduler_cron.sh 

The orange "Running" still shows in your module though. Is there a way to stop or check to ensure that the enterprise page crawler was killed as well? Also - I seem to notice a ton of CRON.log entries like "Pending schedule for "<tasks are listed here>" at "<times listed here>" already exists 1 times. Skipping." Is this a clue? Is there a way to avoid this?

**Comment by bjoern-tantau** [comment]
I disable these long-running tasks and add a manual cron-entry for them with the scheduler shell script. Not sure if it is still run like this, as I am running a quite old version but this is what I run:

````
php /var/www/html/web/shell/scheduler.php -action runNow -code <code>
````

**Comment by Quazz** [comment]
You should assign them a group and run them seperately.

Add the group on the magento admin page and then alter your existing cron schedule to something like

/bin/bash /home/user/public_html/scheduler_cron.sh --excludeGroups crawlergroup --mode default 

and add a new entry

/bin/bash /home/user/public_html/scheduler_cron.sh --includeGroups crawlergroup --mode default 

Now they will run in parallel cron processes and won't block other tasks from running.

**Comment by fbrnc** [comment]
Thanks for the answer @Quazz. That's exactly the way to go.
However, would be interesting to find out why thir particular job takes so long. But that's outside of the scope of the scheduler...

**Comment by brandontamm** [comment]
@fbrnc - I noticed the issue after adding 700 categories and have since disabled the cron completely because I have never manually ran it and successfully finished it. I have been manually running a shell script to warm cache (hack0r :) after FPC refresh (my site doesnt have many updates.)

Is there a way I can use AOEScheduler's parameters to exclude the parent category for the 700 subcategories (I dont need these crawled as they have very little traffic and are more for SEO purposes - see quickattach.com)

Any help would be greatly appreciated?

**Comment by brandontamm** [comment]
Figured this out for anyone with the same issue - 
1) System > Configuration > System > Full Page Cache Auto Generation
2) Gradually Increase Crawler Thread Number (monitor your server resources from start to finish)
3) Use AOEScheduler to schedule the page crawler cache during low traffic hours
4) Use AOE Cache cleaner to schedule a cache clean just prior to your morning cache warm
5) Try not to have 700 categories (hahaha - client requirement, but for real, ridiculous)

@fbrnc - please close :)
