### ISSUE TITLE
Error with composer

### ISSUE THREAD

**Issue by matiaso** [AOEpeople/Aoe_Scheduler#307]
When updating through composer:

` [ErrorException]
  Source [...]/vendor/aoepeople/aoe_scheduler/app/locale/pt_BR/template/email/aoe_scheduler/ does not exist`

**Comment by munkhulzii** [comment]
i confirm this bug. there is no template directory under pt_BR

**Comment by Webmasterei** [comment]
I fixed it by creating the structure there. Please fix in the git too.

**Comment by Julime** [comment]
i can confirm this

**Comment by kirladu** [comment]
confirm!
temporary fix from composer root on shell:
$ mkdir vendor/aoepeople/aoe_scheduler/app/locale/pt_BR/template
$ mv vendor/aoepeople/aoe_scheduler/app/locale/pt_BR/email vendor/aoepeople/aoe_scheduler/app/locale/pt_BR/template

**Comment by kirladu** [comment]
when will there be a release of the fix... got to apply the upper patch almost daily...
