### ISSUE TITLE
Cron groups not being executed due to locking logic in specific scenario

### ISSUE THREAD

**Issue by nemphys** [AOEpeople/Aoe_Scheduler#308]
I just tried to use cron groups for the first time and discovered the following issue:

I added a specific job to a group and then changed the one-liner default execution in crontab to
*  *    * * *   www-data ! test -e /var/www/magento/maintenance.flag && /bin/bash /ssd/magento/scheduler_cron.sh --mode default --includeGroups groupA
*  *    * * *   www-data ! test -e /var/www/magento/maintenance.flag && /bin/bash /ssd/magento/scheduler_cron.sh --mode default --excludeGroups groupA
, hoping that the job in groupA would be executed separately from the other jobs.

What happened is that only one of the two simultaneous executions would take place (either, not a specific one) and the other would be silently ignored.

After a little debugging, I pinpointed the cause to be the lock file name created by scheduler_cron.sh:
${MODE}${INCLUDE_GROUPS}${EXCLUDE_GROUPS}${INCLUDE_JOBS}${EXCLUDE_JOBS},
which of course is identical in both situations, since the excluded/included group names match.

A simple solution is to prepend an identifier to the include/exclude variables, eg:
${MODE}IG${INCLUDE_GROUPS}EG${EXCLUDE_GROUPS}IJ${INCLUDE_JOBS}EJ${EXCLUDE_JOBS},
which effectively differentiates between the two execution runs.

Simple fix and I wonder why nobody stumbled upon this issue, it seems to be a common scenario.

Would greatly appreciate it if this was merged this soon, hate to maintain unincluded commits.

**Comment by LeeSaferite** [comment]
What version of the code are you using? I ask because the temp file name actually uses | between each part and then hashes the string in the master branch.

**Comment by nemphys** [comment]
Right, sorry for this, I am using the master branch but had somehow forgotten to copy the actual scheduler_cron.sh script to the production env (and therefore I am using an old version of the script).
Haven't tested yet, but the current script seems to be OK.

**Comment by nemphys** [comment]
Confirmed that it is working properly, sorry for the trouble.
