### ISSUE TITLE
CPanel's "jailshell" breaks AOE Scheduler

### ISSUE THREAD

**Issue by colinpickup** [AOEpeople/Aoe_Scheduler#311]
The hosting company that my company host our clients with uses WHM/CPanel to administer their servers. Indeed a number of other hosting companies we've used have used CPanel too. A problem that I've started encountering more recently on sites which also employ CPanel's "jailshell" is that the AOE_Scheduler "scheduler_cron.sh" doesn't work when run via it. Using one of the commands reccommended under "setup instructions", such as:

MAILTO="..."
* * * * * /bin/bash /home/site/public_html/scheduler_cron.sh --mode always
* * * * * /bin/bash /home/site/public_html/scheduler_cron.sh --mode default

I find that it generates email output messages such as the following:

>Content-type: text/html; charset=UTF-8
>
>Available actions:
    --action listAllCodes
    --action lastRun --code &lt;code> [--secondsFromNow]   Get the timestamp of the last successful run of a job for a given code
    --action scheduleNow --code &lt;code>  Schedule a job to be executed as soon as possible
    --action runNow --code &lt;code> [--tryLock] [--force]         Run a job directly
    --action disableJob --code &lt;code>           Disable job
    --action enableJob --code &lt;code>            Enable job
    --action wait [--timout &lt;timeout=60>]               Active wait until no schedules are running.
    --action flushSchedules --mode (future|all)         Flush schedules.
    --action listAllRunningSchedules
    --action listGroups
    --action killAll
    --action watchdog
    --action cron --mode (always|default) [--includeJobs &lt;comma separated list of jobs>] [--excludeJobs &lt;comma separated list of jobs>] [--includeGroups &lt;comma separated list of groups>] [--excludeGroups &lt;comma separated list of groups>]

I have tried a few things, including running scheduler.php directly from the cron. The configuration that I have found to work on some servers is to edit the cron.php to set "$isShellDisabled = true" and run the standard cron. On some servers, even that has proven problematic.

Is there any way that the instructions could be altered to add details of how to configure to work under a jailshell? Could it be done with a specifically crafted CRON line? Could the scheduler_cron.sh / scheduler.php files be altered to detect running under a jailshell and run a simplified version?

**Comment by Quazz** [comment]
Seems to be the same issue as https://github.com/AOEpeople/Aoe_Scheduler/issues/299

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/280609348f3fa2db47994cfa3a22cb36806cb41d 
now you can pass path to binary as a param
