### ISSUE TITLE
EasyApache 4 which php problem

### ISSUE THREAD

**Issue by Quazz** [AOEpeople/Aoe_Scheduler#318]
With EasyApache4 (on cPanel), a lot of changes were made to how everything runs.

You now have two PHP binaries, one for cgi (aka displaying webpages and such) and one for cli

The one for cgi is located at /usr/bin/php and the one for cli at /usr/local/bin/php

The script in its current form will select the former, however, which will cause it to fail with a 404 error. 

Manually changing the PHP= variable to /usr/local/bin/php allows the script to work, but of course this gets overwritten with updates. 

I'm not super experienced with bash scripts, but do you think there'd be an easy way to account for this possibility?

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/280609348f3fa2db47994cfa3a22cb36806cb41d
