### ISSUE TITLE
Aoe_Scheduler requires PHP version  >= 5.3.0 and <= 6.0.0 

### ISSUE THREAD

**Issue by WillemRoman** [AOEpeople/Aoe_Scheduler#323]
Is it possible to add PHP 7 support to this package?
While installing this extension via the package manager I got this error since our magento shop runs PHP7

**Comment by robbieaverill** [comment]
Magento 1 does not support PHP7 without an extension, so unsure whether it would be wise to allow it in this package.

**Comment by bahadirdogru** [comment]
magento 1.9.3 and above support php7 without extension but this extension supports? In fact almost all php files supported by php7 but there is some differences. It's most likely supported isn't it?

**Comment by gsomoza** [comment]
bump 👍

**Comment by Aquive** [comment]
PHP7 Support would great since many Magento 1 shops are running on PHP7 (with the needed modifications in place).

**Comment by bahadirdogru** [comment]
I'm using https://github.com/Inchoo/Inchoo_PHP7 and i installed extension manuely. It's working.

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/pull/344
