### ISSUE TITLE
Feature Request: Debug mode

### ISSUE THREAD

**Issue by AydinHassan** [AOEpeople/Aoe_Scheduler#33]
Hey, I have been using this tool recently and it's pretty helpful for running cron's manually and debugging them. One thing I was thinking that would be nice to have, is some kind of option to tell my cron model to output debug information when manually run.

Imagine I have a long export process being triggered by a cron, now I won't want console output because it is being run on the server by the cron user.

If I am running the command manually through `Aoe_Scheduler` I want to output debug information such as the progress of the export. 

How might you implement this feature?

I was thinking we could maybe just set a super global in the `runNow` function and I could just check that in my cron models, however that is not an optimal solution.

Any ideas?

If this is something you would be interested in and we agree on an implementation, i'll create a pull request :)

**Comment by fbrnc** [comment]
Tasks can now accept parameters. I think that's a good option to pass an additional debug flag to your code. Check out version 1.
