### ISSUE TITLE
Remove cronjobs which were never scheduled(_at)

### ISSUE THREAD

**Issue by borriglione** [AOEpeople/Aoe_Scheduler#349]
I faced the problem that cronjobs which were created manually f.e. by:

```php shell/n98-magerun.phar sys:cron:run jobcode```

and failed (f.e. because of a timeout or an exception) were never removed, remained in "running" status and block future cronjobs with the same jobcode so that they won't be executed anymore.

This jobs should be cleaned by ```system/cron/mark_as_error_after``` and ```system/cron/max_job_runtime``` logic too.

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/8ac6266a8bc9ca4b28feee7d401469cc4bdeefc2
