### ISSUE TITLE
PHP 7.0 and 1.9.3.2

### ISSUE THREAD

**Issue by mblatt** [AOEpeople/Aoe_Scheduler#355]
Does anybody know if this module runs with Magento 1.9.3.2 and PHP 7.0 ?

Regards,
Marcus

**Comment by paradoxos** [comment]
i never had a problem with PHP 7.0 yet.

**Comment by m-overlund** [comment]
works fine here...

**Comment by mss-mohdali** [comment]
We are getting error in cron email -
../scheduler_cron.sh: line 179: 20546 Segmentation fault      (core dumped) "${PHP_BIN}" "${SCHEDULER}" --action cron --mode ${MODE} ${OPTIONS}

**Comment by mitcht** [comment]
No problems for my with php 7.2

**Comment by mss-mohdali** [comment]
We are using php-7.0.27 and magento CE- 1.9.3.7 and getting this warning only in cron email except this everything is working fine. @mitcht which version of this extension and magento you are using ? Any solution to fix this issue with php 7.0 and magnento CE - 1.9.3.7 ?

**Comment by tmotyl** [comment]
works fine
