### ISSUE TITLE
Occasionally jobs are not generated for up to 30 minutes

### ISSUE THREAD

**Issue by mzeis** [AOEpeople/Aoe_Scheduler#36]
Cron job scheduling and generation worked perfectly until we upgraded Aoe_Scheduler to the newest version (so that we can use the updates from July 18th and 19th).

In the last days we experienced that new jobs are not scheduled for 20 to 30 minutes. We don't get errors in the logs or high load on the server. It's not at the same time of the day.

It could be that the hiccup starts when/after the history cleanup runs. (Btw. the history cleanup runs twice because we have to cron groups set up).

Information on our setup:

* EE 1.13.0.2
* Aoe_Scheduler @ ffc09f1e83 (last version used before: 2b853e103a)

Cron schedule (filenames and pathes changed):

    * * * * * /usr/bin/env SCHEDULER_WHITELIST='a,b,c,d' /bin/sh /path/to/magento/cron_1.sh cron_1.php -m=default  >> /path/to/log/scron.log 2>&1
    * * * * * /usr/bin/env SCHEDULER_BLACKLIST='a,b,c,d' /bin/sh /path/to/magento/cron_2.sh cron.php -m=default  >> /path/to/logs/cron.log 2>&1

The timeline looks like that:

![aoe_scheduler_timeline_cropped_2014-07-31_1545](https://cloud.githubusercontent.com/assets/371060/3765141/f4502fd4-18b8-11e4-9f1e-21e2218998d0.png)

That manic job at the top is `enterprise_refresh_index`.

There is no hint why the generation stops or starts again.

Our configuration:

![aoe_scheduler_configuration_2014-07-31_1548](https://cloud.githubusercontent.com/assets/371060/3765223/865e2d22-18b9-11e4-8fdb-7e133d1b33be.png)

We do have a long lifetime but we use that setting for a long time now. I thought about setting higher values for "Schedule Ahead for" and "History Cleanup Every" to see if this makes a difference.

If this problem persists we'll downgrade and check if it also happens with the old version.

Any ideas? Thanks!

**Comment by mzeis** [comment]
We didn't experience this problem anymore since #37 was implemented. Is everybody fine with me closing this issue?

**Comment by matthew-muscat** [comment]
Yep - fine on our end with #37

**Comment by shivkumarsingh7** [comment]
Hi @fbrnc 


I am facing a problem with custom email. Email does not sent automatically according to its schedule.

Cron is working fine. I have debug code using Mage::log(). I am getting each log before sendTransactional function after that log is not working.

However its working fine with Aoe_schedule when I run cron forcefully.

But Its not working when it schedule from Aoe_schedule. Execution halt on sendTransactional function.
