### ISSUE TITLE
Compatibility with php7

### ISSUE THREAD

**Issue by lucasalcantara** [AOEpeople/Aoe_Scheduler#369]
This is more like a question and I hope that it is not a problem. I am planning to add this module to my Magento project but it is running with PHP7 and I'd like to know when this module will be compatibility with PHP7.

**Comment by mitcht** [comment]
I'm currently running it on php7.2. It seems to work and I'm not getting error logs full of problems.

**Comment by lucasalcantara** [comment]
Thanks @mitcht.
