### ISSUE TITLE
No heartbeat shown in Backend

### ISSUE THREAD

**Issue by WiiWiiWii** [AOEpeople/Aoe_Scheduler#377]
Hi community,
I have a serious problem with cron jobs. It has been working fine for a long time, but has stopped for some days. If I enter 
php scheduler.php -action lastRun -code aoescheduler_heartbeat -secondsFromNow
I can see that the heartbeat must run. I get outputs from 0 to 299.
But why is the heartbeat no shown in the backend?

<img width="859" alt="bildschirmfoto 2018-06-25 um 17 02 22" src="https://user-images.githubusercontent.com/40572270/41858247-ac603d82-7899-11e8-8bc7-c91bacc20bff.png">
![bildschirmfoto 2018-06-25 um 17 02 50](https://user-images.githubusercontent.com/40572270/41858248-ac809bea-7899-11e8-9c7f-ea8193847742.png)

Cheers
Willi

**Comment by tmotyl** [comment]
Somethig must be missconfigured on youre sever. If you've found a solution please post it here so others can benefit.
