### ISSUE TITLE
AOE Scheduler not working with magento 1.9.3.8 + php7

### ISSUE THREAD

**Issue by darshan1tecstub** [AOEpeople/Aoe_Scheduler#379]
Hello,

We have added AOE Scheduler in my upgraded  magento 1.9.3.8 + php7, but it dose not working properly there, It working fine with  magento 1.7 + php5.6, Dose anyone have solution for it or what we have to change for it? please replay me asap.

**Comment by Quazz** [comment]
Working fine here, most likely you just have to change the PHP path in scheduler_cron.sh
