### ISSUE TITLE
Jobs reported as "gone", completed a few minutes later under other id

### ISSUE THREAD

**Issue by mzeis** [AOEpeople/Aoe_Scheduler#38]
Since we upgraded to ffc09f1e83, some jobs fail as "gone" and are executed and completed two minutes later. Before the process ids were recorded the jobs were just marked complete at the time they were scheduled first. Do you have a guess if this happens because of the way your check is implemented or if this is a server / project issue?

Information on our setup:

* EE 1.13.0.2
* Aoe_Scheduler @ d17bd8a49f (last version without this problem: 2b853e103a)

Cron schedule (filenames and pathes changed):

    * * * * * /usr/bin/env SCHEDULER_WHITELIST='a,b,c,d' /bin/sh /path/to/magento/cron_1.sh cron_1.php -m=default  >> /path/to/log/scron.log 2>&1
    * * * * * /usr/bin/env SCHEDULER_BLACKLIST='a,b,c,d' /bin/sh /path/to/magento/cron_2.sh cron.php -m=default  >> /path/to/logs/cron.log 2>&1

The timeline looks like that:

![timeline_2014-08-05_1034](https://cloud.githubusercontent.com/assets/371060/3808752/70fbbc5e-1c7b-11e4-958c-c30a11bf065b.png)

The failed job:

![cronjob_gone_2014-08-05_1049](https://cloud.githubusercontent.com/assets/371060/3808924/8ba43e9e-1c7d-11e4-96ba-b2581505c376.png)

The message is:

    Process "9227" on host "###" cannot be found anymore

The successful job:

![cronjob_success_2014-08-05_1049](https://cloud.githubusercontent.com/assets/371060/3808926/95504654-1c7d-11e4-8953-36bec1270521.png)

**Comment by mzeis** [comment]
@paales: were you able to solve this problem? We still get the errors.

**Comment by paales** [comment]
@mzeis Never looked at this any more.

**Comment by mzeis** [comment]
@paales Ok, thank you!

**Comment by fbrnc** [comment]
Somebody sent me an email saying his jobs are being marked as gone (but he didn't say anything about them completing with a different process id) and we're experiencing "gone" jobs in one of our projects.

While I expect this being jobs dying with PHP Fatal errors (of the processes being killed outside Aoe_Scheduler) for whatever reason, the fact that more than one Magento instance having an issue related to "gone" jobs makes me wonder if there's actually a bug in the scheduler...

**Comment by grindking** [comment]
I'm not sure whether this is the right thread or not but I'm the one who sent an email to @fbrnc .
There are some crontasks which are marked as gone when I check my timeline:
![timeline](https://cloud.githubusercontent.com/assets/316247/7859202/f8e4eddc-053e-11e5-9e39-b6be7ef98e89.png)

I cannot explain why this jobs are not working properly. I noticed that these are all tasks, which take a little bit more time e.g. 'creating sitemap', 'creating product feed' etc.
First I thought it's an issue of memory-limit or max-execution-time and that is why I contacted our server admins (rackers). They increased the memory but this didn't solve the problem. Maybe you guys have a hint for me.

**Comment by paales** [comment]
@grindking I always run the cron using the shell/scheduler.php to see if it throws any errors, if it doesn't it might be a different problem.

**Comment by grindking** [comment]
@paales Thank you for that. This is what I have tried:
# sudo -u apache php scheduler.php --action runNow --code datafeedmanager_generate
I don't get an error and it doesn't work. When I run the job from the Magento backend 'run now' it works proprly.

**Comment by geoff-webtise** [comment]
Hi,

I am also experiencing the same issue as  grindking, is there though a matrix to explain each status?

**Comment by grindking** [comment]
I am still struggling with this problem. First I thought it's just the feedmanager but there are several tasks which are not working properly. I noticed that these are tasks which take a little longer though.

**Comment by grindking** [comment]
Does anyone already have a solution for this problem?

**Comment by mzeis** [comment]
We upgraded to EE 1.14.2.0 and Aoe_Scheduler 1.2.1 in the meanwhile.

The message is "Process "1234" on host "www.thehost.com" cannot be found anymore", not one of the new error messages.

**Comment by r-nicol** [comment]
Just for more details this happens for me for every single enterprise_refresh_index job. This is on EE 1.14.2.4 and Aoe 1.5.0.

**Comment by mzeis** [comment]
Fun fact: just yesterday I concluded that our problem seems to be gone after a provider switch.

**Comment by mzeis** [comment]
@r-nicol: we're running on AOE 1.5.0 for quite some time now without getting this error. Is it ok for you if I close this issue?

**Comment by svenbolz** [comment]
Just in case anyone else is dealing with the same problem:

To me this sounds like script timeouts and the provider switch led to:
a.) faster processing 
- or -
b.) the timeout variables are set higher on the new system

**Comment by r-nicol** [comment]
Looks like are case was down to SQL errors in mage. Looks stable since we
did that. Happy for this to get closed.
