### ISSUE TITLE
I didnt found the use of parameters

### ISSUE THREAD

**Issue by ravirajm10** [AOEpeople/Aoe_Scheduler#381]
How we can pass the parameters externally to the model method.
I mean how I can retrieve the parameters in the model ? 
Thanks in advance

**Comment by tmotyl** [comment]
Sorry, I don't understand the question. Please be more verbose.

**Comment by onlinebizsoft** [comment]
@tmotyl I have same issue and I understand his question, he meant when we create a custom job and set custom parameter. How can we get/use the parameter value in the model?

**Comment by tmotyl** [comment]
What parameters? Which model?

**Comment by onlinebizsoft** [comment]
@tmotyl never mind. I found out
@ravirajm10 it is too late but maybe someone need

![image](https://user-images.githubusercontent.com/22501570/80588231-26b39780-8a42-11ea-80f7-1a8c4b762889.png)
![image](https://user-images.githubusercontent.com/22501570/80588250-34691d00-8a42-11ea-9640-e74785e1d6a6.png)
