### ISSUE TITLE
event for manually started cronjob

### ISSUE THREAD

**Issue by bragento** [AOEpeople/Aoe_Scheduler#39]
hey,

I would like to implement a new Event that is dispatched, when a cronjob is run by "run now" or "schedule now".

The Reason is, that we would like to get an email notification, when a cron job is run manually (in case it happened accidently)

I would implement the email notification in an own module, except you wish to have it in the scheduler, then I would make a pull Request, where you will be able to activate that feature in the system configuration.

Regards,
David

**Comment by fbrnc** [comment]
This is part of version 1 now.
