### ISSUE TITLE
php 8.1

### ISSUE THREAD

**Issue by Jattura** [AOEpeople/Aoe_Scheduler#399]
Hello, Everfyone

Can someone help? I use the php8.1 of openmage. Timeline view always warns: Last heartbeat was more than an hour ago. Please check your setup and configuration! The line cannot turn green. If anyone knows about this, please suggest how to fix it. Million thanks.

![圖片](https://user-images.githubusercontent.com/127373501/230480328-5553ff28-e81b-4045-942e-ff86ad393b32.png)

**Comment by m-overlund** [comment]
Tested and works fine on PHP8.1 / OpenMage 19.4.23

**Comment by Jattura** [comment]
> Tested and works fine on PHP8.1 / OpenMage 19.4.23

Thanks. Mr m-overlund. I pay freelancers to debug script errors and still have problems instead of solving them. I hope your team can help to regenerate a new php8 or later. Really, without your support. These great extensions won't last long for you. Thank you so much.
