### ISSUE TITLE
Hanging Processes

### ISSUE THREAD

**Issue by curiouscrusher** [AOEpeople/Aoe_Scheduler#45]
Has anybody else experienced issues with certain processes running indefinitely? These processes were created in the future, scheduled in the past, and then executed in the future.. There's also several tasks buried within the running tasks that were missed or pending.
In addition I'm thinking the way AOE is displaying this is a bug of some sort, doesn't seem right. 
![screen shot 2014-11-25 at 10 38 00 am](https://cloud.githubusercontent.com/assets/4745854/5185836/359a138c-7490-11e4-8580-860d85023841.png)
![screen shot 2014-11-25 at 10 39 23 am](https://cloud.githubusercontent.com/assets/4745854/5185838/35aa4bd0-7490-11e4-9ee4-0e676d6b35fb.png)
![screen shot 2014-11-25 at 10 39 55 am](https://cloud.githubusercontent.com/assets/4745854/5185837/35a75fba-7490-11e4-8a86-4ba0ab90ad3c.png)

Specs: 
Magento 1.12.0.2 Enterprise 
Latest version of AOE

**Comment by fbrnc** [comment]
I think this is fixed now. Could you please check if you experience the same issue with the latest version of Aoe_Scheduler?
