### ISSUE TITLE
parallel cronjobs whitelist and blacklist switched

### ISSUE THREAD

**Issue by davidverholen** [AOEpeople/Aoe_Scheduler#56]
Hey,

I'm just testing around with parallel cronjobs and have some weird behaviour. My crontab looks like this:

```
* * * * * /bin/sh /var/www/casamoda/casamodab2c/project/root/cron.sh cron.php -malways 1
* * * * * /usr/bin/env SCHEDULER_BLACKLIST='long_running_process' /bin/sh /var/www/magento/root/cron.sh cron.php -mdefault 1
* * * * * /usr/bin/env SCHEDULER_WHITELIST='long_running_process' /bin/sh /var/www/magento/root/cron.sh cron-slow.php -mdefault 1
```

Now, when I observe the running Processes, the cron.php executes the long_running_process, and the cron-slow.php executes all other processes.

I looked into your code and really can't explain myself, why this happens.

It's not a Problem with 2 cron processes, but it becomes one if you want to have more.

Maybe you have an idea?

**Comment by davidverholen** [comment]
ok this seems to be another Problem.

We have some more jobs in the white/blacklist. Some seem to work right, some not. Yes I checked the spelling multiple times ;)

**Comment by fbrnc** [comment]
Hi David,

we'll be a releasing a new version of Aoe_Scheduler at the end of this week and the blacklist/whitelist feature has been cleaned up significantly. If you still have an issue I suggest you check the new version once it is out. (We'll have to write some documentation on how the new feature works...)

Have a great day,
Fabrizio

**Comment by davidverholen** [comment]
Hey,

good to hear. We will try it :)
today we started using the parallel cronjobs in a productive environment. Seems to work.
I'm not sure why one job was executed by the wrong cron process, yet. Maybe it's fixed with the update then
