### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/Aoe_Scheduler#82]

**Comment by robbieaverill** [comment]
As an alternative, could you remove jQuery and use the Prototype lib that ships with Magento?

**Comment by fbrnc** [comment]
I updated jQuery in the context of #158 (and I'm also adding knockout.js).
@robbieaverill: Feel free to open a new ticket if you feel Aoe_Scheduler should not come with jQuery. Although I like jQuery a lot more and I'm currently rewriting major parts of the JS there's a chance that we could rewrite the code to use Prototype instead (if we really wanted). 
For now I don't want to deal with Prototype, so I'll continue to use jQuery... :)
